-- Generated by scripts/generate-cart-checkout-seed.mjs — do not edit by hand.
-- Logistics, containers, Supply costs, plant backfill, order currencies.

begin;

-- Container types from logistics-demo.json
insert into public.store_container_type (
  code, name, inner_length_mm, inner_width_mm, inner_height_mm, max_weight_kg, sort_order
) values (
  '20ft',
  '20ft',
  5898,
  2352,
  2393,
  28200,
  1
) on conflict (code) do update set
  name = excluded.name,
  inner_length_mm = excluded.inner_length_mm,
  inner_width_mm = excluded.inner_width_mm,
  inner_height_mm = excluded.inner_height_mm,
  max_weight_kg = excluded.max_weight_kg,
  sort_order = excluded.sort_order;
insert into public.store_container_type (
  code, name, inner_length_mm, inner_width_mm, inner_height_mm, max_weight_kg, sort_order
) values (
  '40ft',
  '40ft',
  12032,
  2352,
  2393,
  26700,
  2
) on conflict (code) do update set
  name = excluded.name,
  inner_length_mm = excluded.inner_length_mm,
  inner_width_mm = excluded.inner_width_mm,
  inner_height_mm = excluded.inner_height_mm,
  max_weight_kg = excluded.max_weight_kg,
  sort_order = excluded.sort_order;
insert into public.store_container_type (
  code, name, inner_length_mm, inner_width_mm, inner_height_mm, max_weight_kg, sort_order
) values (
  '40HC',
  '40HC',
  12032,
  2352,
  2690,
  30000,
  3
) on conflict (code) do update set
  name = excluded.name,
  inner_length_mm = excluded.inner_length_mm,
  inner_width_mm = excluded.inner_width_mm,
  inner_height_mm = excluded.inner_height_mm,
  max_weight_kg = excluded.max_weight_kg,
  sort_order = excluded.sort_order;

-- Quantity per unit + logistics for every variant (extra variants copy product logistics)
do $seed$
declare
  r record;
  v_length numeric;
  v_width numeric;
  v_height numeric;
  v_weight numeric;
  v_stacking boolean;
  v_stacking_limit integer;
  v_rotate_length boolean;
  v_rotate_width boolean;
  v_max_per_container integer;
  v_qty integer;
  v_source text;
begin
  for r in
    select v.id as variant_id, v.product_id
    from public.store_product_variant v
    where v.deleted_at is null
  loop
    select
      l.quantity_per_unit,
      l.length_cm,
      l.width_cm,
      l.height_cm,
      l.weight_kg,
      l.stacking,
      l.stacking_limit,
      l.rotate_length,
      l.rotate_width,
      l.max_per_container,
      l.source
    into
      v_qty, v_length, v_width, v_height, v_weight,
      v_stacking, v_stacking_limit, v_rotate_length, v_rotate_width,
      v_max_per_container, v_source
    from (values
      (1, 1, 230, 130, 126, 545, true, null, false, false, 18, 'prod'),
      (2, 1, 189, 71.1, 79.6, 139.4, true, null, false, false, 62, 'estimated'),
      (3, 1, 157, 46, 86, 147.6, true, null, false, false, null, 'prod'),
      (4, 1, 188, 57, 87, 148.6, true, null, false, false, 75, 'prod'),
      (5, 1, 217, 77, 125, 234, true, null, false, false, 30, 'prod'),
      (6, 1, 194.6, 56.9, 91.2, 179, true, null, false, false, 66, 'estimated'),
      (7, 1, 194, 69.7, 87.2, 164.5, true, null, false, false, 56, 'estimated'),
      (8, 1, 130, 74, 62, 112, true, null, false, false, 108, 'prod'),
      (9, 1, 136, 77, 65, 134.5, true, null, false, false, 100, 'prod'),
      (10, 1, 149.5, 80.5, 85, 208, true, null, false, false, 64, 'prod'),
      (11, 1, 149.5, 81, 80.5, 198, true, null, false, false, 66, 'prod'),
      (12, 1, 180, 112, 84, 235, true, null, false, false, 39, 'prod'),
      (13, 1, 115, 70, 61, 116, true, null, false, false, 136, 'prod'),
      (14, 1, 169.5, 114, 85.2, 217, true, null, false, false, 42, 'prod'),
      (15, 1, 170, 115, 86, 220, true, null, false, false, 42, 'prod'),
      (16, 1, 150, 80, 53, 140, true, null, false, false, 115, 'prod'),
      (17, 1, 229, 142, 83, 480, true, null, false, false, 24, 'prod'),
      (18, 1, 206.2, 79, 111.1, 242.3, true, null, false, false, 37, 'estimated'),
      (19, 1, 231.9, 59.6, 93.3, 210.3, true, null, false, false, 51, 'estimated'),
      (20, 1, 231, 132.5, 125, 520, true, 4, false, false, 17, 'prod'),
      (21, 1, 373, 116, 98, 705, true, null, false, false, 3, 'prod'),
      (22, 1, 287, 115, 101, 590, true, null, false, false, 16, 'prod'),
      (23, 1, 148, 36.5, 81, 141, true, null, false, false, 144, 'prod'),
      (24, 1, 147.5, 35.8, 87, 142.28, true, null, false, false, 144, 'prod'),
      (25, 1, 193.6, 57.8, 108.3, 230.1, true, null, false, false, 55, 'estimated'),
      (26, 1, 157.3, 46.5, 86, 154.1, true, null, false, false, 111, 'prod'),
      (27, 1, 228, 82, 115, 331, true, null, false, false, null, 'prod'),
      (28, 1, 238, 76, 124, 342, true, null, false, false, 30, 'prod'),
      (29, 1, 188, 46.5, 88, 160, true, null, false, false, 96, 'prod'),
      (30, 1, 181, 48.5, 86, 171, true, null, false, false, 93, 'prod'),
      (31, 1, 195.5, 57, 126.2, 164.2, true, null, false, false, 48, 'prod'),
      (32, 1, 170, 45, 86, 152, true, null, false, false, 105, 'prod'),
      (33, 1, 192.8, 52.4, 98.7, 176.3, true, null, false, false, 67, 'estimated'),
      (34, 1, 217, 63, 117, 223, true, null, false, false, 38, 'prod'),
      (35, 1, 217, 63, 117, 220, true, null, false, false, 38, 'prod'),
      (36, 1, 241.4, 69.9, 112.6, 252.7, true, null, false, false, 35, 'estimated'),
      (37, 1, 243, 68.4, 113.5, 250.9, true, null, false, false, 35, 'estimated'),
      (38, 1, 222, 75, 124, 238, true, null, false, false, 30, 'prod'),
      (39, 1, 229, 70, 130, 286, true, null, false, false, 33, 'prod'),
      (40, 1, 214.5, 72.6, 111.7, 231.3, true, null, false, false, 38, 'estimated'),
      (41, 1, 177.1, 64, 93, 89.9, true, null, false, false, 63, 'estimated'),
      (42, 1, 177.5, 63.8, 88.6, 85.6, true, null, false, false, 66, 'estimated'),
      (43, 1, 235.5, 126, 66, 317.2, true, null, false, false, 34, 'estimated'),
      (44, 1, 178, 56.5, 85.5, 131.4, true, null, false, false, 78, 'prod'),
      (45, 1, 172.7, 68.3, 85.5, 131.4, true, null, false, false, 66, 'estimated'),
      (46, 1, 195.6, 61.4, 87.5, 186.3, true, null, false, false, 63, 'estimated'),
      (47, 1, 200.4, 58, 93.9, 193.4, true, null, false, false, 61, 'estimated'),
      (48, 1, 196.8, 61.2, 92.2, 196.8, true, null, false, false, 60, 'estimated'),
      (49, 1, 166.5, 80.5, 83.4, 215.3, true, null, false, false, 59, 'estimated'),
      (50, 1, 204, 80, 112, 225, true, null, false, false, 30, 'prod'),
      (51, 1, 217, 84, 122, 265, true, null, false, false, 28, 'prod'),
      (52, 1, 217, 79, 122, 285, true, null, false, false, 28, 'prod'),
      (53, 1, 195, 74, 86, 199, true, null, false, false, 54, 'prod'),
      (54, 1, 215, 65, 126, 240, true, null, false, false, 32, 'prod'),
      (55, 1, 188, 57, 114, 190, true, null, false, false, 50, 'prod'),
      (56, 1, 229, 70, 130, 270, true, null, false, false, 33, 'prod'),
      (57, 1, 229, 84, 130, 324, true, null, false, false, 27, 'prod'),
      (58, 1, 211.6, 86.1, 113.9, 277.9, true, null, false, false, 32, 'estimated'),
      (59, 1, 231.8, 77.4, 119, 285.9, true, null, false, false, 31, 'estimated'),
      (60, 1, 140, 38, 64, 90.5, true, null, false, false, 200, 'prod'),
      (61, 1, 140, 38, 64, 91, true, null, false, false, 200, 'prod'),
      (62, 1, 175.8, 56.6, 87.7, 74.5, true, null, false, false, 76, 'estimated'),
      (63, 1, 229, 84, 125, 272, true, null, false, false, 28, 'prod'),
      (64, 1, 100, 50, 50, 50, true, null, false, false, null, 'estimated'),
      (65, 1, 184.7, 63.4, 96.9, 96.8, true, null, false, false, 59, 'estimated'),
      (66, 1, 170.4, 65.3, 100.1, 95, true, null, false, false, 60, 'estimated'),
      (67, 1, 185.5, 63.1, 92.7, 92.6, true, null, false, false, 61, 'estimated'),
      (68, 1, 311.3, 123.4, 117.6, 661.3, true, null, false, false, 14, 'estimated'),
      (69, 1, 285.3, 129.9, 102.6, 556.7, true, null, false, false, 17, 'estimated'),
      (70, 1, 315, 123.7, 119, 678.8, true, null, false, false, 14, 'estimated'),
      (71, 1, 184.8, 56.6, 122.4, 149.5, true, null, false, false, 52, 'estimated'),
      (72, 1, 207.3, 52.8, 130.7, 167, true, null, false, false, 46, 'estimated'),
      (73, 1, 188.9, 52.9, 118.9, 138.7, true, null, false, false, 56, 'estimated'),
      (74, 1, 210.9, 56.7, 116.7, 162.9, true, null, false, false, 48, 'estimated'),
      (75, 1, 154.2, 36.3, 88.5, 150, true, null, false, false, 135, 'estimated'),
      (76, 1, 148, 39.1, 89.1, 156.1, true, null, false, false, 129, 'estimated'),
      (77, 1, 137, 37, 82.6, 126.8, true, null, false, false, 160, 'estimated'),
      (78, 1, 142.6, 35.7, 81.7, 125.9, true, null, false, false, 161, 'estimated'),
      (79, 1, 140.9, 33.6, 84.9, 121.7, true, null, false, false, 166, 'estimated'),
      (80, 1, 192.5, 64.9, 107.7, 255.5, true, null, false, false, 49, 'estimated'),
      (81, 1, 216.5, 57.6, 103.2, 244.3, true, null, false, false, 52, 'estimated'),
      (82, 1, 221.2, 66, 94.1, 260.8, true, null, false, false, 48, 'estimated'),
      (83, 1, 202.5, 61.9, 101.3, 241.1, true, null, false, false, 52, 'estimated'),
      (84, 1, 219.8, 63.9, 104.8, 279.5, true, null, false, false, 45, 'estimated'),
      (85, 1, 218.2, 61.2, 108.9, 276.1, true, null, false, false, 46, 'estimated'),
      (86, 1, 199.3, 64.1, 94.8, 229.9, true, null, false, false, 55, 'estimated'),
      (87, 1, 208.5, 55, 106.9, 216.7, true, null, false, false, 54, 'estimated'),
      (88, 1, 179.2, 56.1, 96.4, 171.3, true, null, false, false, 69, 'estimated'),
      (89, 1, 202.9, 50.5, 104, 188.4, true, null, false, false, 62, 'estimated'),
      (90, 1, 233, 65.3, 93.8, 232.8, true, null, false, false, 46, 'estimated'),
      (91, 1, 199.9, 54.4, 107.3, 206.3, true, null, false, false, 57, 'estimated'),
      (92, 1, 201.5, 52.1, 103.2, 191.5, true, null, false, false, 61, 'estimated'),
      (93, 1, 204.8, 52.3, 93.6, 177.2, true, null, false, false, 66, 'estimated'),
      (94, 1, 181.9, 56.9, 109.2, 199.8, true, null, false, false, 59, 'estimated'),
      (95, 1, 185.5, 56.9, 99.8, 186.2, true, null, false, false, 63, 'estimated'),
      (96, 1, 185.5, 47.9, 86.1, 173.3, true, null, false, false, 87, 'estimated'),
      (97, 1, 178.1, 46.5, 82.5, 154.8, true, null, false, false, 98, 'estimated'),
      (98, 1, 179.6, 47.5, 87.4, 168.9, true, null, false, false, 89, 'estimated'),
      (99, 1, 235.1, 124.3, 65.9, 311.9, true, null, false, false, 34, 'estimated'),
      (100, 1, 226.3, 128.7, 66.5, 313.7, true, null, false, false, 34, 'estimated'),
      (101, 1, 194.9, 49.3, 80.9, 176.1, true, null, false, false, 86, 'estimated'),
      (102, 1, 223.6, 75.5, 122.4, 274.8, true, null, false, false, 32, 'estimated'),
      (103, 1, 221.7, 74, 115.5, 252, true, null, false, false, 35, 'estimated'),
      (104, 1, 242.7, 70.7, 113.3, 258.6, true, null, false, false, 34, 'estimated'),
      (105, 1, 197.5, 53.2, 96.4, 50.6, true, null, false, false, 66, 'estimated'),
      (106, 1, 209.5, 51.7, 102.3, 55.4, true, null, false, false, 60, 'estimated'),
      (107, 1, 209.4, 63.2, 98.9, 213.5, true, null, false, false, 51, 'estimated'),
      (108, 1, 206.2, 62.3, 92.6, 194, true, null, false, false, 56, 'estimated'),
      (109, 1, 208.1, 63.5, 98.3, 211.9, true, null, false, false, 51, 'estimated'),
      (110, 1, 135.8, 94.9, 68, 152.5, true, null, false, false, 76, 'estimated'),
      (111, 1, 148.4, 86.7, 78, 174.7, true, null, false, false, 66, 'estimated'),
      (112, 1, 141, 88.8, 74.2, 161.7, true, null, false, false, 72, 'estimated'),
      (113, 1, 132.2, 93.2, 77.9, 167, true, null, false, false, 69, 'estimated'),
      (114, 1, 147.5, 98, 77.5, 195, true, null, false, false, 59, 'estimated'),
      (115, 1, 229, 118, 84, 460, true, null, false, false, 30, 'prod'),
      (116, 1, 230, 119.2, 88.7, 443, true, null, false, false, 29, 'prod'),
      (117, 1, 230, 120, 66, 295, true, null, false, false, 40, 'prod'),
      (118, 1, 281.5, 122, 106.6, 535.9, true, null, false, false, 18, 'estimated'),
      (119, 1, 200, 50, 100, 50, false, null, false, false, null, 'prod'),
      (120, 1, 153.9, 45.4, 87.8, 150.1, true, null, false, false, 109, 'estimated'),
      (121, 1, 198.3, 58.7, 88.7, 183, true, null, false, false, 64, 'estimated'),
      (122, 1, 158.3, 42.2, 90.3, 147.6, true, null, false, false, 111, 'estimated'),
      (123, 1, 149, 44.5, 87, 141.18, true, null, false, false, 120, 'prod'),
      (124, 1, 209, 84, 130, 255, true, null, false, false, 27, 'prod'),
      (125, 1, 190, 57, 87, 152, true, null, false, false, 72, 'prod'),
      (126, 1, 189.3, 52.7, 88.8, 157, true, null, false, false, 75, 'estimated'),
      (127, 1, 190, 57, 87, 167, true, null, false, false, 72, 'prod'),
      (128, 1, 209.7, 84.4, 107.4, 254.5, true, null, false, false, 35, 'estimated'),
      (129, 1, 183.3, 57.6, 96.2, 86.7, true, null, false, false, 65, 'estimated'),
      (130, 1, 179.8, 58.6, 89.8, 80.7, true, null, false, false, 70, 'estimated'),
      (131, 1, 181.1, 62.2, 95, 91.3, true, null, false, false, 62, 'estimated'),
      (132, 1, 187.9, 59.8, 98.5, 94.4, true, null, false, false, 60, 'estimated'),
      (133, 1, 183.3, 63.5, 91.6, 91, true, null, false, false, 62, 'estimated'),
      (134, 1, 172.3, 63.9, 90.5, 85, true, null, false, false, 67, 'estimated'),
      (135, 1, 175.8, 58.5, 92.3, 168.2, true, null, false, false, 70, 'estimated'),
      (136, 1, 287.2, 121.4, 103.3, 527.3, true, null, false, false, 18, 'estimated'),
      (137, 1, 180.3, 50.6, 87.8, 181.4, true, null, false, false, 83, 'estimated'),
      (138, 1, 176.6, 44.9, 81.8, 146.9, true, null, false, false, 103, 'estimated'),
      (139, 1, 203.6, 60.8, 134.5, 194.4, true, null, false, false, 40, 'estimated'),
      (140, 1, 203.6, 54.3, 128.4, 165.7, true, null, false, false, 47, 'estimated'),
      (141, 1, 195.1, 60.6, 129, 178.1, true, null, false, false, 43, 'estimated'),
      (142, 1, 139.7, 42.3, 83.7, 121.1, true, null, false, false, 135, 'estimated'),
      (143, 1, 180.3, 73.6, 92.1, 207.9, true, null, false, false, 54, 'estimated'),
      (144, 1, 193.4, 69.8, 88.2, 202.5, true, null, false, false, 56, 'estimated'),
      (145, 1, 201.2, 61.6, 106.3, 214.9, true, null, false, false, 50, 'estimated'),
      (146, 1, 224, 57, 106.8, 258.9, true, null, false, false, 49, 'estimated'),
      (147, 1, 152.1, 86.3, 78.6, 179.6, true, null, false, false, 64, 'estimated'),
      (148, 1, 179.4, 49.3, 83.2, 166.7, true, null, false, false, 91, 'estimated'),
      (149, 1, 199, 55.7, 125.4, 162.3, true, null, false, false, 48, 'estimated'),
      (150, 1, 185.1, 52.8, 86.8, 150.4, true, null, false, false, 78, 'estimated'),
      (151, 1, 208, 78.7, 112, 245.5, true, null, false, false, 36, 'estimated'),
      (152, 1, 220.4, 61.9, 105.1, 272.2, true, null, false, false, 46, 'estimated'),
      (153, 1, 204.9, 65.4, 102.4, 260.5, true, null, false, false, 48, 'estimated'),
      (154, 1, 199.3, 63.1, 94.8, 226.3, true, null, false, false, 56, 'estimated'),
      (155, 1, 164.6, 85.5, 82.4, 223.3, true, null, false, false, 57, 'estimated'),
      (156, 1, 206.5, 60.8, 97.6, 199.9, true, null, false, false, 54, 'estimated'),
      (157, 1, 195.7, 57.3, 100.2, 198.6, true, null, false, false, 59, 'estimated'),
      (158, 1, 157.8, 36.8, 80.9, 142.2, true, null, false, false, 142, 'estimated'),
      (159, 1, 154.5, 35.5, 92.9, 154.3, true, null, false, false, 131, 'estimated'),
      (160, 1, 202.3, 51.3, 98.7, 51.2, true, null, false, false, 65, 'estimated'),
      (161, 1, 205.1, 63.3, 102.5, 252.6, true, null, false, false, 50, 'estimated'),
      (162, 1, 195.7, 59.2, 109.3, 240.4, true, null, false, false, 52, 'estimated'),
      (163, 1, 215.8, 62, 107.8, 273.8, true, null, false, false, 46, 'estimated'),
      (164, 1, 217.5, 59.4, 103.7, 254.4, true, null, false, false, 50, 'estimated'),
      (165, 1, 200.2, 53.9, 97.7, 52.7, true, null, false, false, 63, 'estimated'),
      (166, 1, 198.6, 52.6, 101.7, 53.1, true, null, false, false, 63, 'estimated'),
      (167, 1, 320.1, 116.5, 115.5, 630.6, true, null, false, false, 15, 'estimated'),
      (168, 1, 143, 97, 75.2, 181.5, true, null, false, false, 64, 'estimated'),
      (169, 1, 228.6, 63.2, 107.8, 254, true, null, false, false, 43, 'estimated'),
      (170, 1, 231.4, 69.2, 120.8, 257.3, true, null, false, false, 34, 'estimated'),
      (171, 1, 222, 68, 121.5, 243.9, true, null, false, false, 36, 'estimated'),
      (172, 1, 294.8, 133.8, 106.1, 612.7, true, null, false, false, 16, 'estimated'),
      (173, 1, 202.2, 57.2, 101.1, 222, true, null, false, false, 57, 'estimated'),
      (174, 1, 179.9, 56.7, 80.3, 145.2, true, null, false, false, 81, 'estimated'),
      (175, 1, 181.4, 53.7, 81, 139.9, true, null, false, false, 84, 'estimated'),
      (176, 1, 196.1, 61, 91.9, 194.8, true, null, false, false, 60, 'estimated'),
      (177, 1, 229.3, 68.6, 119.6, 250.2, true, null, false, false, 35, 'estimated'),
      (178, 1, 213.6, 76.7, 117.1, 255.1, true, null, false, false, 34, 'estimated'),
      (179, 1, 174.5, 76.6, 78, 200.8, true, null, false, false, 64, 'estimated'),
      (180, 1, 208.5, 79.9, 106.8, 238.2, true, null, false, false, 37, 'estimated'),
      (181, 1, 196.8, 64.1, 98.5, 235.9, true, null, false, false, 53, 'estimated'),
      (182, 1, 207.2, 63.3, 93.1, 199.2, true, null, false, false, 54, 'estimated'),
      (183, 1, 213.5, 69.6, 117, 231.2, true, null, false, false, 38, 'estimated'),
      (184, 1, 153.8, 34.3, 88.3, 141, true, null, false, false, 143, 'estimated'),
      (185, 1, 207.7, 65.5, 98.9, 255.4, true, null, false, false, 49, 'estimated'),
      (186, 1, 304.1, 115.6, 115, 591.8, true, null, false, false, 16, 'estimated'),
      (187, 1, 208.6, 58.4, 99.4, 229.9, true, null, false, false, 55, 'estimated'),
      (188, 1, 229.7, 122.9, 67.5, 308.6, true, null, false, false, 35, 'estimated'),
      (189, 1, 171.9, 77.1, 90.2, 230.2, true, null, false, false, 56, 'estimated'),
      (190, 1, 183.3, 60.4, 82.3, 127.2, true, null, false, false, 73, 'estimated'),
      (191, 1, 212.9, 80.5, 109.1, 250.4, true, null, false, false, 35, 'estimated'),
      (192, 1, 224.3, 59.1, 95.7, 240.8, true, null, false, false, 52, 'estimated'),
      (193, 1, 205.8, 65.7, 98, 251.6, true, null, false, false, 50, 'estimated'),
      (194, 1, 204, 58.5, 102, 231.1, true, null, false, false, 55, 'estimated'),
      (195, 1, 214.9, 57.1, 107.3, 250, true, null, false, false, 50, 'estimated'),
      (196, 1, 182.8, 55.2, 93.4, 166.6, true, null, false, false, 71, 'estimated'),
      (197, 1, 171.7, 48.4, 83.6, 157.4, true, null, false, false, 96, 'estimated'),
      (198, 1, 202.1, 52.4, 98.6, 52.2, true, null, false, false, 64, 'estimated'),
      (199, 1, 149.1, 89.9, 74.9, 174.7, true, null, false, false, 66, 'estimated'),
      (200, 1, 141.8, 87.1, 74.6, 160.4, true, null, false, false, 72, 'estimated'),
      (201, 1, 208.7, 70, 90.8, 225.7, true, null, false, false, 50, 'estimated'),
      (202, 1, 186.3, 75, 85, 202, true, null, false, false, 56, 'estimated'),
      (203, 1, 200.1, 69.7, 87, 206.4, true, null, false, false, 55, 'estimated'),
      (204, 1, 197, 63.6, 88, 94.1, true, null, false, false, 60, 'estimated'),
      (205, 1, 144.7, 37.8, 87.2, 144.4, true, null, false, false, 140, 'estimated'),
      (206, 1, 223.8, 59.7, 100.7, 219.5, true, null, false, false, 49, 'estimated'),
      (207, 1, 203.8, 50.9, 109.4, 200.6, true, null, false, false, 59, 'estimated')
    ) as l(
      product_id, quantity_per_unit, length_cm, width_cm, height_cm, weight_kg,
      stacking, stacking_limit, rotate_length, rotate_width, max_per_container, source
    )
    where l.product_id = r.product_id;

    if not found then
      -- Fallback for products missing from snapshot
      v_qty := 1;
      v_length := 100;
      v_width := 50;
      v_height := 50;
      v_weight := 50;
      v_stacking := true;
      v_stacking_limit := null;
      v_rotate_length := false;
      v_rotate_width := false;
      v_max_per_container := null;
      v_source := 'estimated';
    end if;

    update public.store_product_variant
    set quantity_per_unit = coalesce(nullif(v_qty, 0), 1)
    where id = r.variant_id;

    insert into public.store_product_variant_logistics (
      product_variant_id, length_cm, width_cm, height_cm, weight_kg,
      stacking, stacking_limit, rotate_length, rotate_width, max_per_container, source
    ) values (
      r.variant_id, v_length, v_width, v_height, v_weight,
      v_stacking, v_stacking_limit, v_rotate_length, v_rotate_width, v_max_per_container, v_source
    ) on conflict (product_variant_id) do update set
      length_cm = excluded.length_cm,
      width_cm = excluded.width_cm,
      height_cm = excluded.height_cm,
      weight_kg = excluded.weight_kg,
      stacking = excluded.stacking,
      stacking_limit = excluded.stacking_limit,
      rotate_length = excluded.rotate_length,
      rotate_width = excluded.rotate_width,
      max_per_container = excluded.max_per_container,
      source = excluded.source;
  end loop;
end;
$seed$;

-- Assign plants to variants that have none (deterministic from product_id)
do $plants$
declare
  r record;
  v_plant bigint;
  v_plants bigint[];
begin
  select array_agg(id order by id) into v_plants
  from public.store_plant
  where deleted_at is null;
  if v_plants is null or cardinality(v_plants) = 0 then
    raise exception 'Нет производственных площадок для сида';
  end if;

  for r in
    select id, product_id
    from public.store_product_variant
    where deleted_at is null and plant_id is null
  loop
    -- Prefer plant from sibling variant of the same product, else hash product_id
    select plant_id into v_plant
    from public.store_product_variant
    where product_id = r.product_id and plant_id is not null and deleted_at is null
    order by id
    limit 1;

    if v_plant is null then
      v_plant := v_plants[1 + ((r.product_id * 17) % cardinality(v_plants))];
    end if;

    update public.store_product_variant
    set plant_id = v_plant
    where id = r.id;
  end loop;
end;
$plants$;

-- Supply costs: ~5–15% for ~80% of variant×region pairs
do $supply$
declare
  v record;
  r record;
  v_seed text;
  v_hash bigint;
  v_skip boolean;
  v_pct numeric;
begin
  for v in
    select id from public.store_product_variant where deleted_at is null
  loop
    for r in
      select id, code from public.store_region where deleted_at is null and active
    loop
      v_seed := v.id::text || ':' || lower(r.code);
      -- FNV-ish hash in SQL via hashtext
      v_hash := abs(hashtext(v_seed)::bigint);
      v_skip := (v_hash % 100) < 20;
      if v_skip then
        continue;
      end if;
      v_pct := 5 + ((v_hash / 100) % 101) * 0.1; -- 5.0 .. 15.0
      insert into public.store_product_supply_cost (product_variant_id, region_id, percent)
      values (v.id, r.id, round(v_pct, 1))
      on conflict (product_variant_id, region_id) do update set percent = excluded.percent;
    end loop;
  end loop;
end;
$supply$;

-- Default order currency per region
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'AE'
  and c.code = 'AED'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'RU'
  and c.code = 'RUB'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'KZ'
  and c.code = 'KZT'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'BY'
  and c.code = 'BYN'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'UZ'
  and c.code = 'USD'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'MX'
  and c.code = 'MXN'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'DE'
  and c.code = 'EUR'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'US'
  and c.code = 'USD'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'IN'
  and c.code = 'INR'
  and c.deleted_at is null
  and r.deleted_at is null;
update public.store_region r
set order_currency_id = c.id
from public.store_currency c
where r.code = 'OM'
  and c.code = 'OMR'
  and c.deleted_at is null
  and r.deleted_at is null;

commit;
