-- Immutable stock adjustment document: write-off, decrease, increase.
-- Additive: new tables + RPC. Existing posting RPCs stay as-is.

begin;

create table public.store_adjustment (
  id bigint generated by default as identity primary key,
  operation text not null,
  warehouse_id bigint not null references public.store_warehouse (id),
  explanation text not null,
  source_document_type text,
  source_document_id bigint,
  status text not null default 'posted',
  created_at timestamptz not null default now(),
  created_by bigint not null default public.store_current_user_id() references public.store_user (id),
  constraint store_adjustment_operation_chk
    check (operation in ('write_off', 'decrease', 'increase')),
  constraint store_adjustment_status_chk
    check (status = 'posted'),
  constraint store_adjustment_explanation_chk
    check (length(btrim(explanation)) > 0),
  constraint store_adjustment_source_pair_chk
    check (
      (source_document_type is null and source_document_id is null)
      or (
        source_document_type in (
          'reservation', 'shipment', 'return', 'transfer', 'production_order', 'output'
        )
        and source_document_id is not null
      )
    )
);

comment on table public.store_adjustment is
  'Posted-only stock adjustment. One operation and one warehouse. Explanation is required. Code ADJ-id is not stored.';
comment on column public.store_adjustment.explanation is
  'Required human reason. Stored on the header, not copied into ledger facts.';
comment on column public.store_adjustment.operation is
  'write_off and decrease post a negative free-warehouse fact; increase posts a positive fact.';

create table public.store_adjustment_line (
  id bigint generated by default as identity primary key,
  adjustment_id bigint not null references public.store_adjustment (id),
  product_id bigint not null references public.store_product (id),
  quantity numeric not null,
  constraint store_adjustment_line_qty_chk check (quantity > 0),
  constraint store_adjustment_line_product_uidx unique (adjustment_id, product_id)
);

comment on table public.store_adjustment_line is
  'Adjustment lines store a positive quantity. Sign is applied by the header operation.';

create index store_adjustment_warehouse_idx on public.store_adjustment (warehouse_id, created_at);
create index store_adjustment_line_doc_idx on public.store_adjustment_line (adjustment_id);

alter table public.store_adjustment enable row level security;
create policy store_adjustment_open_all
  on public.store_adjustment for all using (true) with check (true);
grant select, insert, update, delete on table public.store_adjustment
  to anon, authenticated, service_role;
grant usage, select on sequence public.store_adjustment_id_seq
  to anon, authenticated, service_role;

alter table public.store_adjustment_line enable row level security;
create policy store_adjustment_line_open_all
  on public.store_adjustment_line for all using (true) with check (true);
grant select, insert, update, delete on table public.store_adjustment_line
  to anon, authenticated, service_role;
grant usage, select on sequence public.store_adjustment_line_id_seq
  to anon, authenticated, service_role;

alter table public.store_stock_transaction
  drop constraint if exists store_stock_transaction_document_chk;
alter table public.store_stock_transaction
  add constraint store_stock_transaction_document_chk
    check (document_type in (
      'reservation', 'shipment', 'return', 'transfer', 'production_order', 'output', 'adjustment'
    ));

alter table public.store_document_history
  drop constraint if exists store_document_history_type_chk;
alter table public.store_document_history
  add constraint store_document_history_type_chk
    check (document_type in (
      'reservation', 'shipment', 'return', 'transfer',
      'production_order', 'output', 'adjustment', 'customer_order'
    ));

create or replace function public.store_record_document_history(
  p_document_type text,
  p_document_id bigint,
  p_event_type text,
  p_status text,
  p_expected_end_on date,
  p_created_at timestamptz default now(),
  p_created_by bigint default public.store_current_user_id()
)
returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  if p_document_type not in (
    'reservation', 'shipment', 'return', 'transfer',
    'production_order', 'output', 'adjustment', 'customer_order'
  ) then
    raise exception 'Unknown document type %', p_document_type;
  end if;
  if p_event_type not in ('created', 'status_changed', 'expected_end_changed') then
    raise exception 'Unknown history event %', p_event_type;
  end if;
  insert into public.store_document_history (
    document_type, document_id, event_type, status, expected_end_on, created_at, created_by
  ) values (
    p_document_type, p_document_id, p_event_type, p_status, p_expected_end_on,
    coalesce(p_created_at, now()), coalesce(p_created_by, public.store_current_user_id())
  )
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.store_write_tx(
  p_product_id bigint,
  p_quantity numeric,
  p_location_type text,
  p_location_id bigint,
  p_assigned_to_type text,
  p_assigned_to_id bigint,
  p_document_type text,
  p_document_id bigint
)
returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  if p_quantity = 0 then
    raise exception 'Quantity must not be zero';
  end if;
  if p_location_type not in ('warehouse', 'production_order', 'transfer', 'customer_order') then
    raise exception 'Location type % is not allowed', p_location_type;
  end if;
  if p_document_type not in (
    'reservation', 'shipment', 'return', 'transfer', 'production_order', 'output', 'adjustment'
  ) then
    raise exception 'Document type % is not allowed', p_document_type;
  end if;
  perform public.store_assert_owner(p_assigned_to_type, p_assigned_to_id);
  if p_location_type = 'customer_order' then
    if p_assigned_to_type is distinct from 'order' or p_assigned_to_id is distinct from p_location_id then
      raise exception 'Customer order location must be assigned to the same order';
    end if;
  end if;
  if not exists (select 1 from public.store_product where id = p_product_id) then
    raise exception 'Unknown product %', p_product_id;
  end if;

  insert into public.store_stock_transaction (
    created_at, product_id, quantity,
    location_type, location_id, assigned_to_type, assigned_to_id,
    document_type, document_id
  ) values (
    now(), p_product_id, p_quantity,
    p_location_type, p_location_id, p_assigned_to_type, p_assigned_to_id,
    p_document_type, p_document_id
  )
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.store_code_kind_key(p_kind text)
returns text
language sql
immutable
as $$
  select case p_kind
    when 'customer_order' then 'customerOrder'
    when 'production_order' then 'productionOrder'
    when 'reservation_release' then 'reservationRelease'
    when 'customer_order_line' then 'customerOrderLine'
    when 'production_order_line' then 'productionOrderLine'
    when 'reservation_line' then 'reservationLine'
    when 'reservation_release_line' then 'reservationReleaseLine'
    when 'transfer_line' then 'transferLine'
    when 'transfer_allocation' then 'transferAllocation'
    when 'shipment_line' then 'shipmentLine'
    when 'output_line' then 'outputLine'
    when 'output_allocation' then 'outputAllocation'
    when 'return_line' then 'returnLine'
    when 'adjustment_line' then 'adjustmentLine'
    when 'stock_transaction' then 'stockTransaction'
    else p_kind
  end;
$$;

create or replace function public.store_code(p_kind text, p_id bigint)
returns text
language sql
stable
as $$
  select coalesce(
    nullif(
      (
        select s.code_prefixes ->> public.store_code_kind_key(p_kind)
        from public.store_setting s
        order by s.id
        limit 1
      ),
      ''
    ),
    case p_kind
      when 'product' then 'PRD'
      when 'manufacturer' then 'PLT'
      when 'warehouse' then 'WH'
      when 'region' then 'REG'
      when 'customer_order' then 'OMS'
      when 'production_order' then 'PO'
      when 'reservation' then 'RSV'
      when 'reservation_release' then 'REL'
      when 'transfer' then 'TR'
      when 'shipment' then 'SHP'
      when 'output' then 'OUT'
      when 'return' then 'RET'
      when 'adjustment' then 'ADJ'
      when 'customer_order_line' then 'COL'
      when 'production_order_line' then 'POL'
      when 'reservation_line' then 'RSVL'
      when 'reservation_release_line' then 'RELL'
      when 'transfer_line' then 'TRL'
      when 'transfer_allocation' then 'TRA'
      when 'shipment_line' then 'SHL'
      when 'output_line' then 'OUTL'
      when 'output_allocation' then 'OUA'
      when 'return_line' then 'RETL'
      when 'adjustment_line' then 'ADJL'
      when 'stock_transaction' then 'TXN'
      when 'setting' then 'SET'
      else p_kind
    end
  ) || '-' || p_id::text;
$$;

update public.store_setting
set code_prefixes = coalesce(code_prefixes, '{}'::jsonb)
  || jsonb_strip_nulls(jsonb_build_object(
    'adjustment', coalesce(nullif(code_prefixes ->> 'adjustment', ''), 'ADJ'),
    'adjustmentLine', coalesce(nullif(code_prefixes ->> 'adjustmentLine', ''), 'ADJL')
  ));

create or replace function public.store_create_and_post_adjustment(
  p_operation text,
  p_warehouse_id bigint,
  p_explanation text,
  p_lines jsonb,
  p_source_document_type text default null,
  p_source_document_id bigint default null
)
returns jsonb
language plpgsql
as $$
declare
  v_id bigint;
  v_item record;
  v_signed numeric;
  v_seen bigint[] := '{}';
  v_available numeric;
  v_source_type text;
begin
  if p_operation not in ('write_off', 'decrease', 'increase') then
    raise exception 'Unknown adjustment operation';
  end if;
  if p_warehouse_id is null then
    raise exception 'Выберите склад';
  end if;
  if not exists (select 1 from public.store_warehouse where id = p_warehouse_id) then
    raise exception 'Unknown warehouse %', p_warehouse_id;
  end if;
  if p_explanation is null or length(btrim(p_explanation)) = 0 then
    raise exception 'Укажите объяснение корректировки';
  end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'Добавьте хотя бы одну строку товара';
  end if;

  v_source_type := nullif(btrim(coalesce(p_source_document_type, '')), '');
  if (v_source_type is null) <> (p_source_document_id is null) then
    raise exception 'Ссылка на исходный документ должна быть полной';
  end if;
  if v_source_type is not null then
    if v_source_type not in (
      'reservation', 'shipment', 'return', 'transfer', 'production_order', 'output'
    ) then
      raise exception 'Unknown document type %', v_source_type;
    end if;
  end if;

  insert into public.store_adjustment (
    operation, warehouse_id, explanation, source_document_type, source_document_id, status
  ) values (
    p_operation, p_warehouse_id, btrim(p_explanation), v_source_type, p_source_document_id, 'posted'
  )
  returning id into v_id;

  for v_item in
    select * from jsonb_to_recordset(p_lines) as x(
      product_id bigint,
      quantity numeric
    )
  loop
    if v_item.product_id is null or coalesce(v_item.quantity, 0) <= 0 then
      raise exception 'Количество должно быть больше нуля';
    end if;
    if v_item.product_id = any(v_seen) then
      raise exception 'Один товар можно указать только один раз';
    end if;
    v_seen := array_append(v_seen, v_item.product_id);
    if not exists (select 1 from public.store_product where id = v_item.product_id) then
      raise exception 'Unknown product %', v_item.product_id;
    end if;

    if p_operation in ('write_off', 'decrease') then
      v_available := public.store_qty(v_item.product_id, 'warehouse', p_warehouse_id, null, null);
      if v_available < v_item.quantity then
        raise exception 'Недостаточно свободного остатка в выбранном месте';
      end if;
      v_signed := -v_item.quantity;
    else
      v_signed := v_item.quantity;
    end if;

    insert into public.store_adjustment_line (adjustment_id, product_id, quantity)
    values (v_id, v_item.product_id, v_item.quantity);

    perform public.store_write_tx(
      v_item.product_id, v_signed, 'warehouse', p_warehouse_id,
      null, null, 'adjustment', v_id
    );
  end loop;

  perform public.store_record_document_history(
    'adjustment', v_id, 'created', 'posted', null
  );

  return jsonb_build_object('id', v_id, 'status', 'posted');
end;
$$;

grant execute on function public.store_create_and_post_adjustment(text, bigint, text, jsonb, text, bigint)
  to anon, authenticated, service_role;

create or replace function public.store_cancel_document(p_kind text, p_id bigint)
returns text
language plpgsql
as $$
declare
  v_status text;
begin
  if p_kind in ('reservation', 'reservation_release') then
    raise exception 'Posted reservations cannot be cancelled. Create a Reservation that releases to Free instead.';
  elsif p_kind = 'adjustment' then
    raise exception 'Posted adjustments cannot be cancelled';
  elsif p_kind = 'shipment' then
    select status into v_status from public.store_shipment where id = p_id;
    if v_status is null then
      raise exception 'Unknown shipment %', p_id;
    end if;
    if v_status = 'posted' then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_shipment set status = 'cancelled' where id = p_id;
  elsif p_kind = 'shipment_return' then
    select status into v_status from public.store_return where id = p_id;
    if v_status is null then
      raise exception 'Unknown return %', p_id;
    end if;
    if v_status = 'posted' then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_return set status = 'cancelled' where id = p_id;
  elsif p_kind = 'production_output' then
    select status into v_status from public.store_output where id = p_id;
    if v_status is null then
      raise exception 'Unknown output %', p_id;
    end if;
    if v_status = 'done' then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_output set status = 'cancelled' where id = p_id;
  elsif p_kind = 'transfer' then
    select status into v_status from public.store_transfer where id = p_id;
    if v_status is null then
      raise exception 'Unknown transfer %', p_id;
    end if;
    if v_status in ('sent', 'delivered') then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_transfer set status = 'cancelled' where id = p_id;
  else
    raise exception 'Unknown document kind %', p_kind;
  end if;
  return 'cancelled';
end;
$$;

create or replace function public.store_reset_logistics_stories(p_lo bigint, p_hi bigint)
returns text
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if p_lo is null or p_hi is null or p_lo < 901 or p_hi > 999 or p_lo > p_hi then
    raise exception 'Story reset range must stay inside 901-999';
  end if;

  perform set_config('session_replication_role', 'replica', true);

  delete from public.store_document_history
  where document_id between p_lo and p_hi
     or (document_type = 'customer_order' and document_id between p_lo and p_hi)
     or (document_type = 'reservation' and document_id in (
       select id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     ))
     or (document_type = 'shipment' and document_id in (
       select id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     ))
     or (document_type = 'return' and document_id in (
       select r.id from public.store_return r
       join public.store_shipment s on s.id = r.shipment_id
       where s.customer_order_id between p_lo and p_hi or s.id between p_lo and p_hi or r.id between p_lo and p_hi
     ))
     or (document_type = 'output' and document_id between p_lo and p_hi)
     or (document_type = 'production_order' and document_id between p_lo and p_hi)
     or (document_type = 'transfer' and document_id between p_lo and p_hi)
     or (document_type = 'adjustment' and document_id in (
       select id from public.store_adjustment
       where id between p_lo and p_hi
          or source_document_id between p_lo and p_hi
     ));

  delete from public.store_stock_transaction
  where (assigned_to_type = 'order' and assigned_to_id between p_lo and p_hi)
     or document_id between p_lo and p_hi
     or document_id in (
       select store_reservation.id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     )
     or document_id in (
       select store_shipment.id from public.store_shipment where customer_order_id between p_lo and p_hi
     )
     or document_id in (
       select r.id from public.store_return r
       join public.store_shipment s on s.id = r.shipment_id
       where s.customer_order_id between p_lo and p_hi or s.id between p_lo and p_hi or r.id between p_lo and p_hi
     )
     or document_id in (
       select store_output.id from public.store_output where id between p_lo and p_hi
     )
     or document_id in (
       select store_production_order.id from public.store_production_order where id between p_lo and p_hi
     )
     or document_id in (
       select store_transfer.id from public.store_transfer where id between p_lo and p_hi
     )
     or document_id in (
       select store_adjustment.id from public.store_adjustment
       where id between p_lo and p_hi
          or source_document_id between p_lo and p_hi
     );

  delete from public.store_adjustment_line
  where id between p_lo and p_hi
     or adjustment_id in (
       select id from public.store_adjustment
       where id between p_lo and p_hi
          or source_document_id between p_lo and p_hi
     );

  delete from public.store_adjustment
  where id between p_lo and p_hi
     or source_document_id between p_lo and p_hi;

  delete from public.store_return_line
  where id between p_lo and p_hi
     or return_id in (
       select r.id from public.store_return r
       left join public.store_shipment s on s.id = r.shipment_id
       where r.id between p_lo and p_hi
          or s.id between p_lo and p_hi
          or s.customer_order_id between p_lo and p_hi
     );

  delete from public.store_return
  where id between p_lo and p_hi
     or shipment_id in (
       select store_shipment.id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     );

  delete from public.store_shipment_line
  where id between p_lo and p_hi
     or shipment_id in (
       select store_shipment.id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     );

  delete from public.store_shipment
  where id between p_lo and p_hi or customer_order_id between p_lo and p_hi;

  delete from public.store_output_allocation
  where id between p_lo and p_hi
     or (owner_type = 'order' and owner_id between p_lo and p_hi);

  delete from public.store_output_line where id between p_lo and p_hi or output_id between p_lo and p_hi;
  delete from public.store_output where id between p_lo and p_hi;

  delete from public.store_transfer_request
  where transfer_id between p_lo and p_hi
     or transfer_id in (select id from public.store_transfer where id between p_lo and p_hi);

  delete from public.store_transfer_allocation
  where id between p_lo and p_hi
     or (owner_type = 'order' and owner_id between p_lo and p_hi);

  delete from public.store_transfer_line where id between p_lo and p_hi or transfer_id between p_lo and p_hi;
  delete from public.store_transfer where id between p_lo and p_hi;

  delete from public.store_reservation_line
  where id between p_lo and p_hi
     or (from_owner_type = 'order' and from_owner_id between p_lo and p_hi)
     or reservation_id in (
       select store_reservation.id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     );

  delete from public.store_reservation
  where id between p_lo and p_hi
     or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi);

  delete from public.store_production_order_line where id between p_lo and p_hi or order_id between p_lo and p_hi;
  delete from public.store_production_order where id between p_lo and p_hi;
  delete from public.store_customer_order_line where id between p_lo and p_hi or order_id between p_lo and p_hi;
  delete from public.store_customer_order where id between p_lo and p_hi;

  perform set_config('session_replication_role', 'origin', true);
  return 'reset';
exception
  when others then
    perform set_config('session_replication_role', 'origin', true);
    raise;
end;
$$;

grant execute on function public.store_write_tx(bigint, numeric, text, bigint, text, bigint, text, bigint)
  to anon, authenticated, service_role;
grant execute on function public.store_record_document_history(text, bigint, text, text, date, timestamptz, bigint)
  to anon, authenticated, service_role;
grant execute on function public.store_cancel_document(text, bigint)
  to anon, authenticated, service_role;
grant execute on function public.store_reset_logistics_stories(bigint, bigint)
  to anon, authenticated, service_role;
grant execute on function public.store_code(text, bigint)
  to anon, authenticated, service_role;
grant execute on function public.store_code_kind_key(text)
  to anon, authenticated, service_role;

notify pgrst, 'reload schema';

commit;
