-- Rebuild the stock journal as signed facts, add demo users + document_history,
-- drop reversal and document lifecycle timestamps.

begin;

-- ---------------------------------------------------------------------------
-- 0. Preflight holes + snapshot balances (remapped PO line → parent PO)
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from public.store_stock_transaction
    where reverses_transaction_id is not null or quantity = 0
  ) then
    raise exception 'Journal contains reversals or zero quantities';
  end if;
  if exists (
    select 1 from public.store_stock_transaction t
    where t.location_type = 'production_order_line'
      and not exists (select 1 from public.store_production_order_line pol where pol.id = t.location_id)
  ) then
    raise exception 'Journal production_order_line location has no parent line';
  end if;
  if exists (
    select 1 from public.store_reservation r
    where r.location_type = 'production_order_line'
      and not exists (select 1 from public.store_production_order_line pol where pol.id = r.location_id)
  ) then
    raise exception 'Reservation production_order_line location has no parent line';
  end if;
  if exists (select 1 from public.store_reservation where status = 'posted' and posted_at is null)
    or exists (select 1 from public.store_shipment where status = 'posted' and posted_at is null)
    or exists (select 1 from public.store_return where status = 'posted' and posted_at is null)
    or exists (select 1 from public.store_transfer where status in ('sent', 'delivered') and sent_at is null)
    or exists (select 1 from public.store_output where status = 'done' and done_at is null)
    or exists (select 1 from public.store_customer_order where status = 'closed' and closed_at is null)
    or exists (select 1 from public.store_production_order where status = 'closed' and closed_at is null)
    or exists (select 1 from public.store_shipment where status = 'cancelled' and cancelled_at is null)
    or exists (select 1 from public.store_return where status = 'cancelled' and cancelled_at is null)
    or exists (select 1 from public.store_transfer where status = 'cancelled' and cancelled_at is null)
    or exists (select 1 from public.store_output where status = 'cancelled' and cancelled_at is null)
  then
    raise exception 'Document lifecycle timestamp hole';
  end if;
end;
$$;

create table public.store_fact_balance_before as
select
  t.product_id,
  case when t.location_type = 'production_order_line' then 'production_order' else t.location_type end as location_type,
  case
    when t.location_type = 'production_order_line' then (
      select pol.order_id from public.store_production_order_line pol where pol.id = t.location_id
    )
    else t.location_id
  end as location_id,
  t.owner_type as assigned_to_type,
  t.owner_id as assigned_to_id,
  sum(t.quantity) as quantity
from public.store_stock_transaction t
group by 1, 2, 3, 4, 5
having abs(sum(t.quantity)) > 0.0000001;

-- ---------------------------------------------------------------------------
-- 1. Demo users
-- ---------------------------------------------------------------------------
create table public.store_user (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

comment on table public.store_user is
  'Demo people catalog. created_by on documents and document_history points here. No auth.';

insert into public.store_user (id, name) values
  (1, 'Alexey Nazarov'),
  (2, 'Maria Volkova'),
  (3, 'Ivan Petrov'),
  (4, 'Elena Sokolova'),
  (5, 'Dmitry Orlov');

do $$
begin
  perform setval(
    pg_get_serial_sequence('public.store_user', 'id'),
    (select max(id) from public.store_user)
  );
end;
$$;

alter table public.store_user enable row level security;
create policy store_user_open_all on public.store_user for all using (true) with check (true);
grant select, insert, update, delete on table public.store_user to anon, authenticated, service_role;
grant usage, select on sequence public.store_user_id_seq to anon, authenticated, service_role;

create or replace function public.store_current_user_id()
returns bigint
language sql
immutable
as $$
  select 1::bigint;
$$;

grant execute on function public.store_current_user_id() to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 2. created_by on documents + document_history
-- ---------------------------------------------------------------------------
alter table public.store_customer_order
  add column created_by bigint references public.store_user (id);
alter table public.store_production_order
  add column created_by bigint references public.store_user (id);
alter table public.store_reservation
  add column created_by bigint references public.store_user (id);
alter table public.store_transfer
  add column created_by bigint references public.store_user (id);
alter table public.store_shipment
  add column created_by bigint references public.store_user (id);
alter table public.store_output
  add column created_by bigint references public.store_user (id);
alter table public.store_return
  add column created_by bigint references public.store_user (id);

update public.store_customer_order set created_by = public.store_current_user_id();
update public.store_production_order set created_by = public.store_current_user_id();
alter table public.store_reservation disable trigger user;
update public.store_reservation set created_by = public.store_current_user_id();
alter table public.store_reservation enable trigger user;
update public.store_transfer set created_by = public.store_current_user_id();
update public.store_shipment set created_by = public.store_current_user_id();
update public.store_output set created_by = public.store_current_user_id();
update public.store_return set created_by = public.store_current_user_id();

alter table public.store_customer_order
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;
alter table public.store_production_order
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;
alter table public.store_reservation
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;
alter table public.store_transfer
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;
alter table public.store_shipment
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;
alter table public.store_output
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;
alter table public.store_return
  alter column created_by set default public.store_current_user_id(),
  alter column created_by set not null;

create table public.store_document_history (
  id bigint generated by default as identity primary key,
  document_type text not null,
  document_id bigint not null,
  event_type text not null,
  status text not null,
  expected_end_on date,
  created_at timestamptz not null default now(),
  created_by bigint not null references public.store_user (id),
  constraint store_document_history_type_chk
    check (document_type in (
      'reservation', 'shipment', 'return', 'transfer',
      'production_order', 'output', 'customer_order'
    )),
  constraint store_document_history_event_chk
    check (event_type in ('created', 'status_changed', 'expected_end_changed'))
);

comment on table public.store_document_history is
  'Append-only snapshots after create and each status or expected_end_on change.';

create index store_document_history_document_idx
  on public.store_document_history (document_type, document_id, created_at);

alter table public.store_document_history enable row level security;
create policy store_document_history_open_all
  on public.store_document_history for all using (true) with check (true);
grant select, insert, update, delete on table public.store_document_history
  to anon, authenticated, service_role;
grant usage, select on sequence public.store_document_history_id_seq
  to anon, authenticated, service_role;

create or replace function public.store_record_document_history(
  p_document_type text,
  p_document_id bigint,
  p_event_type text,
  p_status text,
  p_expected_end_on date,
  p_created_at timestamptz default now(),
  p_created_by bigint default public.store_current_user_id()
)
returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  if p_document_type not in (
    'reservation', 'shipment', 'return', 'transfer',
    'production_order', 'output', 'customer_order'
  ) then
    raise exception 'Unknown document type %', p_document_type;
  end if;
  if p_event_type not in ('created', 'status_changed', 'expected_end_changed') then
    raise exception 'Unknown history event %', p_event_type;
  end if;
  insert into public.store_document_history (
    document_type, document_id, event_type, status, expected_end_on, created_at, created_by
  ) values (
    p_document_type, p_document_id, p_event_type, p_status, p_expected_end_on,
    coalesce(p_created_at, now()), coalesce(p_created_by, public.store_current_user_id())
  )
  returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.store_record_document_history(text, bigint, text, text, date, timestamptz, bigint)
  to anon, authenticated, service_role;

-- Backfill: created + current status when it differs
insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'customer_order', id, 'created',
  case when status = 'closed' then 'open' else status end,
  expected_end_on, created_at, created_by
from public.store_customer_order;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'customer_order', id, 'status_changed', status, expected_end_on, closed_at, created_by
from public.store_customer_order
where status = 'closed';

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'reservation', id, 'created', 'draft', null, created_at, created_by
from public.store_reservation;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'reservation', id, 'status_changed', status, null, posted_at, created_by
from public.store_reservation
where status = 'posted';

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'shipment', id, 'created', 'draft', null, created_at, created_by
from public.store_shipment;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'shipment', id, 'status_changed', status, null, coalesce(posted_at, cancelled_at), created_by
from public.store_shipment
where status <> 'draft';

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'return', id, 'created', 'draft', null, created_at, created_by
from public.store_return;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'return', id, 'status_changed', status, null, coalesce(posted_at, cancelled_at), created_by
from public.store_return
where status <> 'draft';

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'transfer', id, 'created', 'sent', expected_end_on, created_at, created_by
from public.store_transfer;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'transfer', id, 'status_changed', status, expected_end_on, coalesce(sent_at, cancelled_at, created_at), created_by
from public.store_transfer
where status <> 'sent';

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'output', id, 'created', 'planned', expected_end_on, created_at, created_by
from public.store_output;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'output', id, 'status_changed', status, expected_end_on, coalesce(done_at, cancelled_at), created_by
from public.store_output
where status <> 'planned';

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'production_order', id, 'created',
  case when status in ('closed', 'cancelled') then 'draft' else status end,
  expected_end_on, created_at, created_by
from public.store_production_order;

insert into public.store_document_history (
  document_type, document_id, event_type, status, expected_end_on, created_at, created_by
)
select 'production_order', id, 'status_changed', status, expected_end_on,
  coalesce(closed_at, created_at), created_by
from public.store_production_order
where status in ('closed', 'cancelled');

create or replace function public.store_document_history_trigger()
returns trigger
language plpgsql
as $$
declare
  v_type text;
  v_expected date;
begin
  v_type := case tg_table_name
    when 'store_customer_order' then 'customer_order'
    when 'store_production_order' then 'production_order'
    when 'store_reservation' then 'reservation'
    when 'store_transfer' then 'transfer'
    when 'store_shipment' then 'shipment'
    when 'store_output' then 'output'
    when 'store_return' then 'return'
    else null
  end;
  if v_type is null then
    return new;
  end if;

  v_expected := case
    when tg_table_name in (
      'store_customer_order', 'store_production_order', 'store_transfer', 'store_output'
    ) then new.expected_end_on
    else null
  end;

  if tg_op = 'INSERT' then
    perform public.store_record_document_history(
      v_type, new.id, 'created', new.status, v_expected, new.created_at, new.created_by
    );
    return new;
  end if;

  if new.status is distinct from old.status then
    perform public.store_record_document_history(
      v_type, new.id, 'status_changed', new.status, v_expected, now(), public.store_current_user_id()
    );
  end if;

  if tg_table_name in (
    'store_customer_order', 'store_production_order', 'store_transfer', 'store_output'
  ) and new.expected_end_on is distinct from old.expected_end_on then
    perform public.store_record_document_history(
      v_type, new.id, 'expected_end_changed', new.status, v_expected, now(), public.store_current_user_id()
    );
  end if;

  return new;
end;
$$;

create trigger store_customer_order_history
  after insert or update of status, expected_end_on on public.store_customer_order
  for each row execute function public.store_document_history_trigger();
create trigger store_production_order_history
  after insert or update of status, expected_end_on on public.store_production_order
  for each row execute function public.store_document_history_trigger();
create trigger store_reservation_history
  after insert or update of status on public.store_reservation
  for each row execute function public.store_document_history_trigger();
create trigger store_transfer_history
  after insert or update of status, expected_end_on on public.store_transfer
  for each row execute function public.store_document_history_trigger();
create trigger store_shipment_history
  after insert or update of status on public.store_shipment
  for each row execute function public.store_document_history_trigger();
create trigger store_output_history
  after insert or update of status, expected_end_on on public.store_output
  for each row execute function public.store_document_history_trigger();
create trigger store_return_history
  after insert or update of status on public.store_return
  for each row execute function public.store_document_history_trigger();

alter table public.store_customer_order drop column closed_at;
alter table public.store_production_order drop column closed_at;
alter table public.store_reservation drop column posted_at;
alter table public.store_transfer drop column sent_at, drop column cancelled_at;
alter table public.store_shipment drop column posted_at, drop column cancelled_at;
alter table public.store_output drop column done_at, drop column cancelled_at;
alter table public.store_return drop column posted_at, drop column cancelled_at;

-- ---------------------------------------------------------------------------
-- 3. Rebuild journal
-- ---------------------------------------------------------------------------
drop view if exists public.store_stock_balance;
drop trigger if exists store_stock_transaction_owner_guard on public.store_stock_transaction;

create table public.store_stock_transaction_next (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  product_id bigint not null references public.store_product (id),
  quantity numeric not null,
  location_type text not null,
  location_id bigint not null,
  assigned_to_type text,
  assigned_to_id bigint,
  document_type text not null,
  document_id bigint not null,
  constraint store_stock_transaction_qty_chk check (quantity <> 0),
  constraint store_stock_transaction_location_chk
    check (location_type in ('warehouse', 'production_order', 'transfer', 'customer_order')),
  constraint store_stock_transaction_assigned_pair_chk
    check (
      (assigned_to_type is null and assigned_to_id is null)
      or (assigned_to_type in ('order', 'region') and assigned_to_id is not null)
    ),
  constraint store_stock_transaction_document_chk
    check (document_type in (
      'reservation', 'shipment', 'return', 'transfer', 'production_order', 'output'
    )),
  constraint store_stock_transaction_customer_assigned_chk
    check (
      location_type <> 'customer_order'
      or (assigned_to_type = 'order' and assigned_to_id = location_id)
    )
);

insert into public.store_stock_transaction_next (
  id, created_at, product_id, quantity,
  location_type, location_id, assigned_to_type, assigned_to_id,
  document_type, document_id
)
select
  t.transaction_id,
  t.posted_at,
  t.product_id,
  t.quantity,
  case when t.location_type = 'production_order_line' then 'production_order' else t.location_type end,
  case
    when t.location_type = 'production_order_line' then (
      select pol.order_id from public.store_production_order_line pol where pol.id = t.location_id
    )
    else t.location_id
  end,
  t.owner_type,
  t.owner_id,
  case t.source_type
    when 'reservation' then 'reservation'
    when 'shipment' then 'shipment'
    when 'shipment_return' then 'return'
    when 'transfer_send' then 'transfer'
    when 'transfer_complete' then 'transfer'
    when 'production_activation' then 'production_order'
    when 'production_close' then 'production_order'
    when 'production_output' then 'output'
    else t.source_type
  end,
  t.source_id
from public.store_stock_transaction t;

drop table public.store_stock_transaction;
alter table public.store_stock_transaction_next rename to store_stock_transaction;

do $$
begin
  perform setval(
    pg_get_serial_sequence('public.store_stock_transaction', 'id'),
    coalesce((select max(id) from public.store_stock_transaction), 1)
  );
end;
$$;

create index store_stock_transaction_balance_idx
  on public.store_stock_transaction (
    product_id, location_type, location_id, assigned_to_type, assigned_to_id
  );
create index store_stock_transaction_document_idx
  on public.store_stock_transaction (document_type, document_id);
create index store_stock_transaction_created_idx
  on public.store_stock_transaction (created_at desc);

comment on table public.store_stock_transaction is
  'Immutable signed stock facts. One row = one product. Direction is the sign of quantity.';
comment on column public.store_stock_transaction.id is 'Former transaction_id.';
comment on column public.store_stock_transaction.created_at is 'Former posted_at.';
comment on column public.store_stock_transaction.assigned_to_type is 'order | region | null (free).';
comment on column public.store_stock_transaction.document_type is
  'Document class: reservation | shipment | return | transfer | production_order | output.';

alter table public.store_stock_transaction enable row level security;
create policy store_stock_transaction_open_all
  on public.store_stock_transaction for all using (true) with check (true);
grant select, insert, update, delete on table public.store_stock_transaction
  to anon, authenticated, service_role;
do $$
declare
  v_seq text;
begin
  v_seq := pg_get_serial_sequence('public.store_stock_transaction', 'id');
  if v_seq is not null then
    execute format('alter sequence if exists %s rename to store_stock_transaction_id_seq', v_seq);
  end if;
end;
$$;
grant usage, select on sequence public.store_stock_transaction_id_seq
  to anon, authenticated, service_role;

create or replace view public.store_stock_balance as
select
  product_id,
  location_type,
  location_id,
  assigned_to_type,
  assigned_to_id,
  sum(quantity) as quantity
from public.store_stock_transaction
group by product_id, location_type, location_id, assigned_to_type, assigned_to_id
having abs(sum(quantity)) > 0.0000001;

grant select on public.store_stock_balance to anon, authenticated, service_role;

-- Reservation location: production_order instead of line
alter table public.store_reservation
  drop constraint if exists store_reservation_location_type_chk,
  drop constraint if exists store_reservation_location_type_check,
  drop constraint if exists logistics_reservation_location_type_check;
alter table public.store_reservation disable trigger user;
update public.store_reservation r
set location_type = 'production_order',
    location_id = pol.order_id
from public.store_production_order_line pol
where r.location_type = 'production_order_line'
  and r.location_id = pol.id;
alter table public.store_reservation enable trigger user;

alter table public.store_reservation
  add constraint store_reservation_location_type_chk
    check (location_type in ('warehouse', 'production_order', 'transfer'));

-- ---------------------------------------------------------------------------
-- 4. Drop old ledger primitives and rewrite RPCs
-- ---------------------------------------------------------------------------
drop function if exists public.store_reverse_source(text, bigint);
drop function if exists public.store_write_tx(bigint, numeric, text, bigint, text, text, bigint, text, bigint, bigint, text, text, bigint, timestamptz);
drop function if exists public.store_move(bigint, numeric, text, bigint, text, bigint, text, text, text, bigint, text, bigint, text, bigint, bigint, text, text);
drop function if exists public.store_qty(bigint, text, bigint, text, text, bigint);

create or replace function public.store_owner_row_guard()
returns trigger
language plpgsql
as $$
begin
  if tg_table_name = 'store_reservation' then
    perform public.store_assert_owner(new.to_owner_type, new.to_owner_id);
  elsif tg_table_name = 'store_reservation_line' then
    perform public.store_assert_owner(new.from_owner_type, new.from_owner_id);
  elsif tg_table_name = 'store_stock_transaction' then
    perform public.store_assert_owner(new.assigned_to_type, new.assigned_to_id);
  elsif tg_table_name in ('store_transfer_allocation', 'store_output_allocation') then
    perform public.store_assert_owner(new.owner_type, new.owner_id);
  end if;
  return new;
end;
$$;

create trigger store_stock_transaction_assigned_guard
  before insert or update on public.store_stock_transaction
  for each row execute function public.store_owner_row_guard();

create or replace function public.store_qty(
  p_product_id bigint,
  p_location_type text,
  p_location_id bigint,
  p_assigned_to_type text,
  p_assigned_to_id bigint
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(quantity), 0)
  from public.store_stock_transaction
  where product_id = p_product_id
    and location_type = p_location_type
    and location_id = p_location_id
    and assigned_to_type is not distinct from p_assigned_to_type
    and assigned_to_id is not distinct from p_assigned_to_id;
$$;

create or replace function public.store_reserved_for_owner_product(
  p_owner_type text,
  p_owner_id bigint,
  p_product_id bigint
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(quantity), 0)
  from public.store_stock_transaction
  where assigned_to_type is not distinct from p_owner_type
    and assigned_to_id is not distinct from p_owner_id
    and product_id = p_product_id
    and location_type <> 'customer_order';
$$;

create or replace function public.store_shipped_for_owner_product(
  p_owner_type text,
  p_owner_id bigint,
  p_product_id bigint
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(quantity), 0)
  from public.store_stock_transaction
  where location_type = 'customer_order'
    and assigned_to_type is not distinct from p_owner_type
    and assigned_to_id is not distinct from p_owner_id
    and product_id = p_product_id;
$$;

create or replace function public.store_write_tx(
  p_product_id bigint,
  p_quantity numeric,
  p_location_type text,
  p_location_id bigint,
  p_assigned_to_type text,
  p_assigned_to_id bigint,
  p_document_type text,
  p_document_id bigint
)
returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  if p_quantity = 0 then
    raise exception 'Quantity must not be zero';
  end if;
  if p_location_type not in ('warehouse', 'production_order', 'transfer', 'customer_order') then
    raise exception 'Location type % is not allowed', p_location_type;
  end if;
  if p_document_type not in (
    'reservation', 'shipment', 'return', 'transfer', 'production_order', 'output'
  ) then
    raise exception 'Document type % is not allowed', p_document_type;
  end if;
  perform public.store_assert_owner(p_assigned_to_type, p_assigned_to_id);
  if p_location_type = 'customer_order' then
    if p_assigned_to_type is distinct from 'order' or p_assigned_to_id is distinct from p_location_id then
      raise exception 'Customer order location must be assigned to the same order';
    end if;
  end if;
  if not exists (select 1 from public.store_product where id = p_product_id) then
    raise exception 'Unknown product %', p_product_id;
  end if;

  insert into public.store_stock_transaction (
    created_at, product_id, quantity,
    location_type, location_id, assigned_to_type, assigned_to_id,
    document_type, document_id
  ) values (
    now(), p_product_id, p_quantity,
    p_location_type, p_location_id, p_assigned_to_type, p_assigned_to_id,
    p_document_type, p_document_id
  )
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.store_move(
  p_product_id bigint,
  p_quantity numeric,
  p_from_type text,
  p_from_id bigint,
  p_to_type text,
  p_to_id bigint,
  p_from_assigned_type text,
  p_from_assigned_id bigint,
  p_to_assigned_type text,
  p_to_assigned_id bigint,
  p_document_type text,
  p_document_id bigint
)
returns void
language plpgsql
as $$
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be positive';
  end if;
  if public.store_qty(
    p_product_id, p_from_type, p_from_id, p_from_assigned_type, p_from_assigned_id
  ) < p_quantity then
    raise exception 'Not enough stock for %', p_product_id;
  end if;

  perform public.store_write_tx(
    p_product_id, -p_quantity, p_from_type, p_from_id,
    p_from_assigned_type, p_from_assigned_id, p_document_type, p_document_id
  );
  perform public.store_write_tx(
    p_product_id, p_quantity, p_to_type, p_to_id,
    p_to_assigned_type, p_to_assigned_id, p_document_type, p_document_id
  );
end;
$$;

create or replace function public.store_post_reservation(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_reservation%rowtype;
  v_line public.store_reservation_line%rowtype;
  v_order_line public.store_customer_order_line%rowtype;
  v_open numeric;
begin
  select * into strict v_doc from public.store_reservation where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.location_type not in ('warehouse', 'production_order', 'transfer') then
    raise exception 'Reservation location type % is not allowed', v_doc.location_type;
  end if;
  if not exists (select 1 from public.store_reservation_line where reservation_id = p_id) then
    raise exception 'Reservation % has no lines', p_id;
  end if;
  perform public.store_assert_owner(v_doc.to_owner_type, v_doc.to_owner_id);

  for v_line in
    select * from public.store_reservation_line where reservation_id = p_id order by id
  loop
    if public.store_owners_equal(
      v_line.from_owner_type, v_line.from_owner_id, v_doc.to_owner_type, v_doc.to_owner_id
    ) then
      raise exception 'Reservation cannot move quantity to the same owner';
    end if;
    if v_doc.to_owner_type is null and v_line.from_owner_type is null then
      raise exception 'Reservation cannot move free to free';
    end if;

    if v_doc.to_owner_type = 'order' then
      select * into v_order_line
      from public.store_customer_order_line
      where order_id = v_doc.to_owner_id and product_id = v_line.product_id;
      if v_order_line.id is null then
        raise exception 'Customer order does not contain this product';
      end if;
      v_open := v_order_line.quantity
        - public.store_shipped_for_owner_product('order', v_doc.to_owner_id, v_line.product_id)
        - public.store_reserved_for_owner_product('order', v_doc.to_owner_id, v_line.product_id);
      if v_line.quantity > v_open then
        raise exception 'Cannot reserve more than the open customer order quantity';
      end if;
    end if;

    perform public.store_move(
      v_line.product_id, v_line.quantity,
      v_doc.location_type, v_doc.location_id, v_doc.location_type, v_doc.location_id,
      v_line.from_owner_type, v_line.from_owner_id,
      v_doc.to_owner_type, v_doc.to_owner_id,
      'reservation', p_id
    );
  end loop;

  update public.store_reservation set status = 'posted' where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.store_close_customer_order(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_loc record;
  v_line record;
  v_res_id bigint;
begin
  if exists (select 1 from public.store_customer_order where id = p_id and status = 'closed') then
    return 'closed';
  end if;

  for v_loc in
    select location_type, location_id
    from public.store_stock_transaction
    where assigned_to_type = 'order' and assigned_to_id = p_id and location_type <> 'customer_order'
    group by 1, 2
    having sum(quantity) > 0
    order by 1, 2
  loop
    insert into public.store_reservation (
      location_type, location_id, to_owner_type, to_owner_id, status, origin, note
    ) values (
      v_loc.location_type, v_loc.location_id, null, null, 'draft', 'order_close', 'Order closed'
    )
    returning id into v_res_id;

    for v_line in
      select product_id, sum(quantity) as qty
      from public.store_stock_transaction
      where assigned_to_type = 'order'
        and assigned_to_id = p_id
        and location_type = v_loc.location_type
        and location_id = v_loc.location_id
      group by 1
      having sum(quantity) > 0
      order by 1
    loop
      insert into public.store_reservation_line (
        reservation_id, product_id, quantity, from_owner_type, from_owner_id
      ) values (
        v_res_id, v_line.product_id, v_line.qty, 'order', p_id
      );
    end loop;

    perform public.store_post_reservation(v_res_id);
  end loop;

  update public.store_customer_order set status = 'closed' where id = p_id;
  return 'closed';
end;
$$;

create or replace function public.store_close_production_order(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_hold record;
  v_line record;
  v_res_id bigint;
  r record;
begin
  if exists (select 1 from public.store_production_order where id = p_id and status = 'closed') then
    return 'closed';
  end if;

  for v_hold in
    select assigned_to_type, assigned_to_id
    from public.store_stock_transaction
    where location_type = 'production_order'
      and location_id = p_id
      and assigned_to_type is not null
    group by 1, 2
    having sum(quantity) > 0
    order by 1, 2
  loop
    insert into public.store_reservation (
      location_type, location_id, to_owner_type, to_owner_id, status, origin, note
    ) values (
      'production_order', p_id, null, null, 'draft', 'order_close', 'Production order closed'
    )
    returning id into v_res_id;

    for v_line in
      select product_id, sum(quantity) as qty
      from public.store_stock_transaction
      where location_type = 'production_order'
        and location_id = p_id
        and assigned_to_type is not distinct from v_hold.assigned_to_type
        and assigned_to_id is not distinct from v_hold.assigned_to_id
      group by 1
      having sum(quantity) > 0
      order by 1
    loop
      insert into public.store_reservation_line (
        reservation_id, product_id, quantity, from_owner_type, from_owner_id
      ) values (
        v_res_id, v_line.product_id, v_line.qty, v_hold.assigned_to_type, v_hold.assigned_to_id
      );
    end loop;

    perform public.store_post_reservation(v_res_id);
  end loop;

  if exists (
    select 1
    from public.store_stock_transaction
    where location_type = 'production_order'
      and location_id = p_id
      and assigned_to_type is not null
    group by product_id, assigned_to_type, assigned_to_id
    having sum(quantity) > 0
  ) then
    raise exception 'Cannot close a production order while reserved quantity remains';
  end if;

  for r in
    select product_id, assigned_to_type, assigned_to_id, sum(quantity) as qty
    from public.store_stock_transaction
    where location_type = 'production_order' and location_id = p_id
    group by 1, 2, 3
    having sum(quantity) > 0
  loop
    perform public.store_write_tx(
      r.product_id, -r.qty, 'production_order', p_id,
      r.assigned_to_type, r.assigned_to_id,
      'production_order', p_id
    );
  end loop;

  update public.store_production_order set status = 'closed' where id = p_id;
  return 'closed';
end;
$$;

create or replace function public.store_post_shipment(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_shipment%rowtype;
  v_line public.store_shipment_line%rowtype;
  v_order_line public.store_customer_order_line%rowtype;
  v_shipped numeric;
begin
  select * into strict v_doc from public.store_shipment where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled documents cannot be posted';
  end if;

  for v_line in select * from public.store_shipment_line where shipment_id = p_id
  loop
    select * into v_order_line
    from public.store_customer_order_line
    where order_id = v_doc.customer_order_id and product_id = v_line.product_id;
    if v_order_line.id is null then
      raise exception 'Shipment line must match the single customer order';
    end if;
    v_shipped := public.store_shipped_for_owner_product('order', v_doc.customer_order_id, v_line.product_id);
    if v_shipped + v_line.quantity > v_order_line.quantity then
      raise exception 'Cannot ship more than the ordered quantity';
    end if;
    perform public.store_move(
      v_line.product_id, v_line.quantity,
      'warehouse', v_doc.warehouse_id, 'customer_order', v_doc.customer_order_id,
      'order', v_doc.customer_order_id,
      'order', v_doc.customer_order_id,
      'shipment', p_id
    );
  end loop;

  update public.store_shipment set status = 'posted' where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.store_post_return(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_return%rowtype;
  v_ship public.store_shipment%rowtype;
  v_line public.store_return_line%rowtype;
  v_ship_line public.store_shipment_line%rowtype;
  v_already numeric;
begin
  select * into strict v_doc from public.store_return where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled documents cannot be posted';
  end if;
  select * into strict v_ship from public.store_shipment where id = v_doc.shipment_id;
  if v_ship.status <> 'posted' then
    raise exception 'Return requires a posted shipment';
  end if;

  for v_line in select * from public.store_return_line where return_id = p_id
  loop
    select * into strict v_ship_line from public.store_shipment_line where id = v_line.shipment_line_id;
    select coalesce(sum(rl.quantity), 0) into v_already
    from public.store_return_line rl
    join public.store_return r on r.id = rl.return_id
    where rl.shipment_line_id = v_line.shipment_line_id
      and r.status = 'posted'
      and r.id <> p_id;
    if v_already + v_line.quantity > v_ship_line.quantity then
      raise exception 'Return cannot exceed the shipped quantity';
    end if;
    perform public.store_move(
      v_ship_line.product_id, v_line.quantity,
      'customer_order', v_ship.customer_order_id, 'warehouse', v_ship.warehouse_id,
      'order', v_ship.customer_order_id,
      null, null,
      'return', p_id
    );
  end loop;

  update public.store_return set status = 'posted' where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.store_send_transfer(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_transfer%rowtype;
  v_line public.store_transfer_line%rowtype;
  v_alloc public.store_transfer_allocation%rowtype;
  v_allocated numeric;
  v_free numeric;
begin
  select * into strict v_doc from public.store_transfer where id = p_id;
  if v_doc.status in ('sent', 'delivered') then
    return v_doc.status;
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled documents cannot be posted';
  end if;

  for v_line in select * from public.store_transfer_line where transfer_id = p_id
  loop
    select coalesce(sum(quantity), 0) into v_allocated
    from public.store_transfer_allocation
    where line_id = v_line.id;
    if v_allocated > v_line.quantity then
      raise exception 'Allocated quantity cannot exceed the document line';
    end if;
    v_free := v_line.quantity - v_allocated;

    for v_alloc in select * from public.store_transfer_allocation where line_id = v_line.id
    loop
      perform public.store_assert_owner(v_alloc.owner_type, v_alloc.owner_id);
      perform public.store_move(
        v_line.product_id, v_alloc.quantity,
        'warehouse', v_doc.from_warehouse_id, 'transfer', p_id,
        v_alloc.owner_type, v_alloc.owner_id,
        v_alloc.owner_type, v_alloc.owner_id,
        'transfer', p_id
      );
    end loop;

    if v_free > 0 then
      perform public.store_move(
        v_line.product_id, v_free,
        'warehouse', v_doc.from_warehouse_id, 'transfer', p_id,
        null, null, null, null,
        'transfer', p_id
      );
    end if;
  end loop;

  update public.store_transfer set status = 'sent' where id = p_id;
  return 'sent';
end;
$$;

create or replace function public.store_complete_transfer(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_transfer%rowtype;
  r record;
begin
  select * into strict v_doc from public.store_transfer where id = p_id;
  if v_doc.status = 'delivered' then
    return 'delivered';
  end if;
  if v_doc.status <> 'sent' then
    raise exception 'Transfer must be sent before it can be delivered';
  end if;

  for r in
    select product_id, assigned_to_type, assigned_to_id, sum(quantity) as qty
    from public.store_stock_transaction
    where location_type = 'transfer' and location_id = p_id
    group by 1, 2, 3
    having sum(quantity) > 0
  loop
    perform public.store_move(
      r.product_id, r.qty,
      'transfer', p_id, 'warehouse', v_doc.to_warehouse_id,
      r.assigned_to_type, r.assigned_to_id,
      r.assigned_to_type, r.assigned_to_id,
      'transfer', p_id
    );
  end loop;

  update public.store_transfer set status = 'delivered' where id = p_id;
  return 'delivered';
end;
$$;

create or replace function public.store_complete_output(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_output%rowtype;
  v_order public.store_production_order%rowtype;
  v_mfr public.store_manufacturer%rowtype;
  v_line public.store_output_line%rowtype;
  v_prod_line public.store_production_order_line%rowtype;
  v_already numeric;
  v_remain numeric;
  v_take numeric;
  r record;
begin
  select * into strict v_doc from public.store_output where id = p_id;
  if v_doc.status = 'done' then
    return 'done';
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled outputs cannot be completed';
  end if;
  if exists (
    select 1 from public.store_stock_transaction
    where document_type = 'output' and document_id = p_id
  ) then
    update public.store_output set status = 'done' where id = p_id;
    return 'done';
  end if;
  select * into strict v_order from public.store_production_order where id = v_doc.production_order_id;
  if v_order.status in ('closed', 'cancelled') then
    raise exception 'Cannot output from a closed production order';
  end if;
  select * into strict v_mfr from public.store_manufacturer where id = v_order.manufacturer_id;

  for v_line in select * from public.store_output_line where output_id = p_id
  loop
    select * into strict v_prod_line
    from public.store_production_order_line
    where id = v_line.production_order_line_id;
    if v_prod_line.product_id <> v_line.product_id then
      raise exception 'Output product must match the production order line';
    end if;
    select coalesce(sum(ol.quantity), 0) into v_already
    from public.store_output_line ol
    join public.store_output o on o.id = ol.output_id
    where ol.production_order_line_id = v_line.production_order_line_id
      and o.status = 'done';
    if v_already + v_line.quantity > v_prod_line.quantity then
      raise exception 'Cannot output more than the production order line';
    end if;

    v_remain := v_line.quantity;

    for r in
      select assigned_to_type, assigned_to_id, sum(quantity) as qty
      from public.store_stock_transaction
      where location_type = 'production_order'
        and location_id = v_order.id
        and product_id = v_line.product_id
        and assigned_to_type is not null
      group by 1, 2
      having sum(quantity) > 0
      order by assigned_to_type, assigned_to_id
    loop
      exit when v_remain <= 0;
      v_take := least(r.qty, v_remain);
      perform public.store_move(
        v_line.product_id, v_take,
        'production_order', v_order.id, 'warehouse', v_mfr.warehouse_id,
        r.assigned_to_type, r.assigned_to_id,
        r.assigned_to_type, r.assigned_to_id,
        'output', p_id
      );
      v_remain := v_remain - v_take;
    end loop;

    if v_remain > 0 then
      perform public.store_move(
        v_line.product_id, v_remain,
        'production_order', v_order.id, 'warehouse', v_mfr.warehouse_id,
        null, null, null, null,
        'output', p_id
      );
    end if;
  end loop;

  update public.store_output set status = 'done' where id = p_id;
  return 'done';
end;
$$;

create or replace function public.store_sync_production_activation(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_order public.store_production_order%rowtype;
  v_line public.store_production_order_line%rowtype;
  v_delta numeric;
begin
  select * into strict v_order from public.store_production_order where id = p_id;
  if v_order.status in ('cancelled', 'closed') then
    return v_order.status;
  end if;

  for v_line in select * from public.store_production_order_line where order_id = p_id
  loop
    v_delta := v_line.quantity - v_line.activated_quantity;
    if v_delta > 0 then
      perform public.store_write_tx(
        v_line.product_id, v_delta, 'production_order', p_id,
        null, null, 'production_order', p_id
      );
      update public.store_production_order_line
      set activated_quantity = activated_quantity + v_delta
      where id = v_line.id;
    elsif v_delta < 0 then
      if public.store_qty(v_line.product_id, 'production_order', p_id, null, null) < -v_delta then
        raise exception 'Not enough unused production quantity to reduce the line';
      end if;
      perform public.store_write_tx(
        v_line.product_id, v_delta, 'production_order', p_id,
        null, null, 'production_order', p_id
      );
      update public.store_production_order_line
      set activated_quantity = v_line.quantity
      where id = v_line.id;
    end if;
  end loop;
  return v_order.status;
end;
$$;

create or replace function public.store_cancel_document(p_kind text, p_id bigint)
returns text
language plpgsql
as $$
declare
  v_status text;
begin
  if p_kind in ('reservation', 'reservation_release') then
    raise exception 'Posted reservations cannot be cancelled. Create a Reservation that releases to Free instead.';
  elsif p_kind = 'shipment' then
    select status into v_status from public.store_shipment where id = p_id;
    if v_status is null then
      raise exception 'Unknown shipment %', p_id;
    end if;
    if v_status = 'posted' then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_shipment set status = 'cancelled' where id = p_id;
  elsif p_kind = 'shipment_return' then
    select status into v_status from public.store_return where id = p_id;
    if v_status is null then
      raise exception 'Unknown return %', p_id;
    end if;
    if v_status = 'posted' then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_return set status = 'cancelled' where id = p_id;
  elsif p_kind = 'production_output' then
    select status into v_status from public.store_output where id = p_id;
    if v_status is null then
      raise exception 'Unknown output %', p_id;
    end if;
    if v_status = 'done' then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_output set status = 'cancelled' where id = p_id;
  elsif p_kind = 'transfer' then
    select status into v_status from public.store_transfer where id = p_id;
    if v_status is null then
      raise exception 'Unknown transfer %', p_id;
    end if;
    if v_status in ('sent', 'delivered') then
      raise exception 'Posted warehouse documents cannot be cancelled';
    end if;
    update public.store_transfer set status = 'cancelled' where id = p_id;
  else
    raise exception 'Unknown document kind %', p_kind;
  end if;
  return 'cancelled';
end;
$$;

create or replace function public.store_reset_logistics_stories(p_lo bigint, p_hi bigint)
returns text
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if p_lo is null or p_hi is null or p_lo < 901 or p_hi > 999 or p_lo > p_hi then
    raise exception 'Story reset range must stay inside 901-999';
  end if;

  perform set_config('session_replication_role', 'replica', true);

  delete from public.store_document_history
  where document_id between p_lo and p_hi
     or (document_type = 'customer_order' and document_id between p_lo and p_hi)
     or (document_type = 'reservation' and document_id in (
       select id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     ))
     or (document_type = 'shipment' and document_id in (
       select id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     ))
     or (document_type = 'return' and document_id in (
       select r.id from public.store_return r
       join public.store_shipment s on s.id = r.shipment_id
       where s.customer_order_id between p_lo and p_hi or s.id between p_lo and p_hi or r.id between p_lo and p_hi
     ))
     or (document_type = 'output' and document_id between p_lo and p_hi)
     or (document_type = 'production_order' and document_id between p_lo and p_hi)
     or (document_type = 'transfer' and document_id between p_lo and p_hi);

  delete from public.store_stock_transaction
  where (assigned_to_type = 'order' and assigned_to_id between p_lo and p_hi)
     or document_id between p_lo and p_hi
     or document_id in (
       select store_reservation.id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     )
     or document_id in (
       select store_shipment.id from public.store_shipment where customer_order_id between p_lo and p_hi
     )
     or document_id in (
       select r.id from public.store_return r
       join public.store_shipment s on s.id = r.shipment_id
       where s.customer_order_id between p_lo and p_hi or s.id between p_lo and p_hi or r.id between p_lo and p_hi
     )
     or document_id in (
       select store_output.id from public.store_output where id between p_lo and p_hi
     )
     or document_id in (
       select store_production_order.id from public.store_production_order where id between p_lo and p_hi
     )
     or document_id in (
       select store_transfer.id from public.store_transfer where id between p_lo and p_hi
     );

  delete from public.store_return_line
  where id between p_lo and p_hi
     or return_id in (
       select r.id from public.store_return r
       left join public.store_shipment s on s.id = r.shipment_id
       where r.id between p_lo and p_hi
          or s.id between p_lo and p_hi
          or s.customer_order_id between p_lo and p_hi
     );

  delete from public.store_return
  where id between p_lo and p_hi
     or shipment_id in (
       select store_shipment.id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     );

  delete from public.store_shipment_line
  where id between p_lo and p_hi
     or shipment_id in (
       select store_shipment.id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     );

  delete from public.store_shipment
  where id between p_lo and p_hi or customer_order_id between p_lo and p_hi;

  delete from public.store_output_allocation
  where id between p_lo and p_hi
     or (owner_type = 'order' and owner_id between p_lo and p_hi);

  delete from public.store_output_line where id between p_lo and p_hi or output_id between p_lo and p_hi;
  delete from public.store_output where id between p_lo and p_hi;

  delete from public.store_transfer_request
  where transfer_id between p_lo and p_hi
     or transfer_id in (select id from public.store_transfer where id between p_lo and p_hi);

  delete from public.store_transfer_allocation
  where id between p_lo and p_hi
     or (owner_type = 'order' and owner_id between p_lo and p_hi);

  delete from public.store_transfer_line where id between p_lo and p_hi or transfer_id between p_lo and p_hi;
  delete from public.store_transfer where id between p_lo and p_hi;

  delete from public.store_reservation_line
  where id between p_lo and p_hi
     or (from_owner_type = 'order' and from_owner_id between p_lo and p_hi)
     or reservation_id in (
       select store_reservation.id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     );

  delete from public.store_reservation
  where id between p_lo and p_hi
     or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi);

  delete from public.store_production_order_line where id between p_lo and p_hi or order_id between p_lo and p_hi;
  delete from public.store_production_order where id between p_lo and p_hi;
  delete from public.store_customer_order_line where id between p_lo and p_hi or order_id between p_lo and p_hi;
  delete from public.store_customer_order where id between p_lo and p_hi;

  perform set_config('session_replication_role', 'origin', true);
  return 'reset';
exception
  when others then
    perform set_config('session_replication_role', 'origin', true);
    raise;
end;
$$;

grant execute on function public.store_qty(bigint, text, bigint, text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_reserved_for_owner_product(text, bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.store_shipped_for_owner_product(text, bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.store_write_tx(bigint, numeric, text, bigint, text, bigint, text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_move(bigint, numeric, text, bigint, text, bigint, text, bigint, text, bigint, text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_post_reservation(bigint) to anon, authenticated, service_role;
grant execute on function public.store_close_customer_order(bigint) to anon, authenticated, service_role;
grant execute on function public.store_close_production_order(bigint) to anon, authenticated, service_role;
grant execute on function public.store_post_shipment(bigint) to anon, authenticated, service_role;
grant execute on function public.store_post_return(bigint) to anon, authenticated, service_role;
grant execute on function public.store_send_transfer(bigint) to anon, authenticated, service_role;
grant execute on function public.store_complete_transfer(bigint) to anon, authenticated, service_role;
grant execute on function public.store_complete_output(bigint) to anon, authenticated, service_role;
grant execute on function public.store_sync_production_activation(bigint) to anon, authenticated, service_role;
grant execute on function public.store_cancel_document(text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_reset_logistics_stories(bigint, bigint) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5. Balance check
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from (
      select * from public.store_fact_balance_before
      except
      select product_id, location_type, location_id, assigned_to_type, assigned_to_id, sum(quantity)
      from public.store_stock_transaction
      group by 1, 2, 3, 4, 5
      having abs(sum(quantity)) > 0.0000001
    ) missing
  ) or exists (
    select 1 from (
      select product_id, location_type, location_id, assigned_to_type, assigned_to_id, sum(quantity)
      from public.store_stock_transaction
      group by 1, 2, 3, 4, 5
      having abs(sum(quantity)) > 0.0000001
      except
      select * from public.store_fact_balance_before
    ) extra
  ) then
    raise exception 'Fact journal migration changed product+location+assigned_to totals';
  end if;
  if exists (
    select 1 from public.store_stock_transaction where location_type = 'production_order_line'
  ) then
    raise exception 'production_order_line remains in the journal';
  end if;
end;
$$;

drop table public.store_fact_balance_before;

notify pgrst, 'reload schema';

commit;
