-- Unified Reservation: one document model for reserve and release.
-- Migrates legacy RSV/REL (and customer_order_close ledger identity) without changing balances.

begin;

-- ---------------------------------------------------------------------------
-- 0. Capture balances for self-validation
-- ---------------------------------------------------------------------------
create table logistics_balance_before as
select
  product_id,
  location_type,
  location_id,
  stock_state,
  customer_order_id,
  customer_order_line_id,
  quantity
from public.logistics_stock_balance;

-- ---------------------------------------------------------------------------
-- 1. Rename legacy tables
-- ---------------------------------------------------------------------------
alter table public.logistics_reservation rename to logistics_reservation_legacy;
alter table public.logistics_reservation_line rename to logistics_reservation_line_legacy;
alter table public.logistics_reservation_release rename to logistics_reservation_release_legacy;
alter table public.logistics_reservation_release_line rename to logistics_reservation_release_line_legacy;

-- ---------------------------------------------------------------------------
-- 2. New canonical tables
-- ---------------------------------------------------------------------------
create table public.logistics_reservation (
  id bigint generated by default as identity primary key,
  customer_order_id bigint not null references public.logistics_customer_order (id),
  location_type text not null,
  location_id bigint not null,
  operation text not null,
  status text not null default 'draft',
  origin text not null default 'manual',
  note text not null default '',
  created_at timestamptz not null default now(),
  posted_at timestamptz,
  constraint logistics_reservation_location_type_check
    check (location_type in ('warehouse', 'production_order_line', 'transfer')),
  constraint logistics_reservation_operation_check
    check (operation in ('reserve', 'release')),
  constraint logistics_reservation_status_check
    check (status in ('draft', 'posted')),
  constraint logistics_reservation_origin_check
    check (origin in ('manual', 'order_close')),
  constraint logistics_reservation_posted_at_check
    check (status <> 'posted' or posted_at is not null)
);

create table public.logistics_reservation_line (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.logistics_reservation (id) on delete cascade,
  customer_order_line_id bigint not null references public.logistics_customer_order_line (id),
  quantity numeric not null,
  constraint logistics_reservation_line_quantity_check check (quantity > 0),
  constraint logistics_reservation_line_unique unique (reservation_id, customer_order_line_id)
);

create index logistics_reservation_order_idx on public.logistics_reservation (customer_order_id);
create index logistics_reservation_location_idx on public.logistics_reservation (location_type, location_id);
create index logistics_reservation_operation_idx on public.logistics_reservation (operation);
create index logistics_reservation_line_order_line_idx on public.logistics_reservation_line (customer_order_line_id);

alter table public.logistics_reservation enable row level security;
alter table public.logistics_reservation_line enable row level security;

create policy logistics_reservation_all on public.logistics_reservation
  for all to anon, authenticated using (true) with check (true);
create policy logistics_reservation_line_all on public.logistics_reservation_line
  for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on table public.logistics_reservation to anon, authenticated, service_role;
grant select, insert, update, delete on table public.logistics_reservation_line to anon, authenticated, service_role;
grant usage, select on sequence public.logistics_reservation_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.logistics_reservation_line_id_seq to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. Posted immutability + line ownership validation
-- ---------------------------------------------------------------------------
create or replace function public.logistics_reservation_enforce_draft_only()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    if old.status = 'posted' then
      raise exception 'Posted reservations are immutable';
    end if;
    return old;
  end if;
  if old.status = 'posted' then
    raise exception 'Posted reservations are immutable';
  end if;
  return new;
end;
$$;

create trigger logistics_reservation_immutable_posted
  before update or delete on public.logistics_reservation
  for each row execute function public.logistics_reservation_enforce_draft_only();

create or replace function public.logistics_reservation_line_guard()
returns trigger
language plpgsql
as $$
declare
  v_doc public.logistics_reservation%rowtype;
  v_order_id bigint;
begin
  if tg_op = 'DELETE' then
    select * into strict v_doc from public.logistics_reservation where id = old.reservation_id;
    if v_doc.status = 'posted' then
      raise exception 'Posted reservations are immutable';
    end if;
    return old;
  end if;

  select * into strict v_doc from public.logistics_reservation where id = new.reservation_id;
  if v_doc.status = 'posted' then
    raise exception 'Posted reservations are immutable';
  end if;

  select order_id into v_order_id
  from public.logistics_customer_order_line
  where id = new.customer_order_line_id;
  if v_order_id is null then
    raise exception 'Unknown customer order line %', new.customer_order_line_id;
  end if;
  if v_order_id <> v_doc.customer_order_id then
    raise exception 'Reservation line must belong to the customer order';
  end if;

  return new;
end;
$$;

create trigger logistics_reservation_line_guard_trg
  before insert or update or delete on public.logistics_reservation_line
  for each row execute function public.logistics_reservation_line_guard();

-- ---------------------------------------------------------------------------
-- 4. Migrate documents (split multi-location legacy docs)
-- Insert as draft → lines → promote to posted so immutability triggers stay happy.
-- ---------------------------------------------------------------------------
create table logistics_rsv_doc_map (
  legacy_kind text not null,
  legacy_id bigint not null,
  location_type text not null,
  location_id bigint not null,
  new_id bigint not null,
  primary key (legacy_kind, legacy_id, location_type, location_id)
);

create table logistics_rsv_line_map (
  legacy_kind text not null,
  legacy_line_id bigint not null,
  new_line_id bigint not null,
  new_reservation_id bigint not null,
  primary key (legacy_kind, legacy_line_id)
);

do $$
declare
  v_doc record;
  v_loc record;
  v_line record;
  v_new_id bigint;
  v_new_line_id bigint;
  v_final_status text;
begin
  for v_doc in
    select * from public.logistics_reservation_legacy order by id
  loop
    v_final_status := case when v_doc.status = 'posted' then 'posted' else 'draft' end;
    for v_loc in
      select location_type, location_id
      from public.logistics_reservation_line_legacy
      where reservation_id = v_doc.id
      group by location_type, location_id
      order by location_type, location_id
    loop
      insert into public.logistics_reservation (
        customer_order_id, location_type, location_id, operation, status, origin, note, created_at, posted_at
      ) values (
        v_doc.customer_order_id,
        v_loc.location_type,
        v_loc.location_id,
        'reserve',
        'draft',
        'manual',
        '',
        v_doc.created_at,
        null
      )
      returning id into v_new_id;

      insert into logistics_rsv_doc_map (legacy_kind, legacy_id, location_type, location_id, new_id)
      values ('reservation', v_doc.id, v_loc.location_type, v_loc.location_id, v_new_id);

      for v_line in
        select *
        from public.logistics_reservation_line_legacy
        where reservation_id = v_doc.id
          and location_type = v_loc.location_type
          and location_id = v_loc.location_id
        order by id
      loop
        insert into public.logistics_reservation_line (
          reservation_id, customer_order_line_id, quantity
        ) values (
          v_new_id, v_line.customer_order_line_id, v_line.quantity
        )
        returning id into v_new_line_id;

        insert into logistics_rsv_line_map (legacy_kind, legacy_line_id, new_line_id, new_reservation_id)
        values ('reservation', v_line.id, v_new_line_id, v_new_id);
      end loop;

      if v_final_status = 'posted' then
        update public.logistics_reservation
        set status = 'posted',
            posted_at = coalesce(v_doc.posted_at, v_doc.created_at)
        where id = v_new_id;
      end if;
    end loop;
  end loop;
end;
$$;

do $$
declare
  v_doc record;
  v_loc record;
  v_line record;
  v_new_id bigint;
  v_new_line_id bigint;
  v_final_status text;
  v_origin text;
begin
  for v_doc in
    select * from public.logistics_reservation_release_legacy order by id
  loop
    v_final_status := case when v_doc.status = 'posted' then 'posted' else 'draft' end;
    v_origin := case
      when lower(trim(coalesce(v_doc.reason, ''))) in ('order closed', 'order close') then 'order_close'
      else 'manual'
    end;
    for v_loc in
      select location_type, location_id
      from public.logistics_reservation_release_line_legacy
      where release_id = v_doc.id
      group by location_type, location_id
      order by location_type, location_id
    loop
      insert into public.logistics_reservation (
        customer_order_id, location_type, location_id, operation, status, origin, note, created_at, posted_at
      ) values (
        v_doc.customer_order_id,
        v_loc.location_type,
        v_loc.location_id,
        'release',
        'draft',
        v_origin,
        coalesce(v_doc.reason, ''),
        v_doc.created_at,
        null
      )
      returning id into v_new_id;

      insert into logistics_rsv_doc_map (legacy_kind, legacy_id, location_type, location_id, new_id)
      values ('reservation_release', v_doc.id, v_loc.location_type, v_loc.location_id, v_new_id);

      for v_line in
        select *
        from public.logistics_reservation_release_line_legacy
        where release_id = v_doc.id
          and location_type = v_loc.location_type
          and location_id = v_loc.location_id
        order by id
      loop
        insert into public.logistics_reservation_line (
          reservation_id, customer_order_line_id, quantity
        ) values (
          v_new_id, v_line.customer_order_line_id, v_line.quantity
        )
        returning id into v_new_line_id;

        insert into logistics_rsv_line_map (legacy_kind, legacy_line_id, new_line_id, new_reservation_id)
        values ('reservation_release', v_line.id, v_new_line_id, v_new_id);
      end loop;

      if v_final_status = 'posted' then
        update public.logistics_reservation
        set status = 'posted',
            posted_at = coalesce(v_doc.posted_at, v_doc.created_at)
        where id = v_new_id;
      end if;
    end loop;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Remap ledger source identity (quantities untouched)
-- ---------------------------------------------------------------------------
update public.logistics_stock_transaction t
set
  source_type = 'reservation',
  source_id = m.new_reservation_id,
  source_line_id = m.new_line_id
from logistics_rsv_line_map m
where t.source_type = 'reservation'
  and m.legacy_kind = 'reservation'
  and t.source_line_id = m.legacy_line_id;

update public.logistics_stock_transaction t
set
  source_type = 'reservation',
  source_id = m.new_reservation_id,
  source_line_id = m.new_line_id
from logistics_rsv_line_map m
where t.source_type = 'reservation_release'
  and m.legacy_kind = 'reservation_release'
  and t.source_line_id = m.legacy_line_id;

-- Fallback when source_line_id is null: match legacy doc + location
update public.logistics_stock_transaction t
set
  source_type = 'reservation',
  source_id = d.new_id
from logistics_rsv_doc_map d
where t.source_type in ('reservation', 'reservation_release')
  and (
    (t.source_type = 'reservation' and d.legacy_kind = 'reservation')
    or (t.source_type = 'reservation_release' and d.legacy_kind = 'reservation_release')
  )
  and t.source_id = d.legacy_id
  and t.location_type = d.location_type
  and t.location_id = d.location_id
  and not exists (
    select 1 from public.logistics_reservation r where r.id = t.source_id and r.id = d.new_id
  )
  and not exists (
    select 1 from public.logistics_reservation r where r.id = t.source_id
  );

-- Remap customer_order_close free/reserved movements onto order_close Reservations
with close_lines as (
  select
    r.customer_order_id,
    r.location_type,
    r.location_id,
    l.customer_order_line_id,
    r.id as reservation_id,
    l.id as reservation_line_id
  from public.logistics_reservation r
  join public.logistics_reservation_line l on l.reservation_id = r.id
  where r.operation = 'release' and r.origin = 'order_close'
)
update public.logistics_stock_transaction t
set
  source_type = 'reservation',
  source_id = c.reservation_id,
  source_line_id = c.reservation_line_id
from close_lines c
where t.source_type = 'customer_order_close'
  and t.source_id = c.customer_order_id
  and t.location_type = c.location_type
  and t.location_id = c.location_id
  and t.customer_order_line_id = c.customer_order_line_id
  and t.stock_state in ('reserved', 'free');

-- Synthesize order_close Reservations for any remaining close ledger rows
do $$
declare
  v_groups record;
  v_res_id bigint;
  v_line_id bigint;
begin
  for v_groups in
    select
      customer_order_id,
      location_type,
      location_id,
      customer_order_line_id,
      abs(sum(case when stock_state = 'reserved' then quantity else 0 end)) as qty,
      min(posted_at) as posted_at
    from public.logistics_stock_transaction
    where source_type = 'customer_order_close'
      and stock_state in ('reserved', 'free')
      and customer_order_id is not null
      and customer_order_line_id is not null
    group by 1, 2, 3, 4
    having abs(sum(case when stock_state = 'reserved' then quantity else 0 end)) > 0
  loop
    select r.id into v_res_id
    from public.logistics_reservation r
    where r.customer_order_id = v_groups.customer_order_id
      and r.location_type = v_groups.location_type
      and r.location_id = v_groups.location_id
      and r.operation = 'release'
      and r.origin = 'order_close'
    order by r.id
    limit 1;

    if v_res_id is null then
      insert into public.logistics_reservation (
        customer_order_id, location_type, location_id, operation, status, origin, note, created_at, posted_at
      ) values (
        v_groups.customer_order_id,
        v_groups.location_type,
        v_groups.location_id,
        'release',
        'draft',
        'order_close',
        'Order closed',
        v_groups.posted_at,
        null
      )
      returning id into v_res_id;
    end if;

    select l.id into v_line_id
    from public.logistics_reservation_line l
    where l.reservation_id = v_res_id
      and l.customer_order_line_id = v_groups.customer_order_line_id;

    if v_line_id is null then
      -- Parent may already be posted from a previous group at this location
      if exists (select 1 from public.logistics_reservation where id = v_res_id and status = 'posted') then
        update public.logistics_reservation set status = 'draft', posted_at = null where id = v_res_id;
      end if;
      insert into public.logistics_reservation_line (
        reservation_id, customer_order_line_id, quantity
      ) values (
        v_res_id, v_groups.customer_order_line_id, greatest(v_groups.qty, 0.0000001)
      )
      returning id into v_line_id;
    end if;

    update public.logistics_reservation
    set status = 'posted', posted_at = coalesce(posted_at, v_groups.posted_at, now())
    where id = v_res_id and status = 'draft';

    update public.logistics_stock_transaction t
    set
      source_type = 'reservation',
      source_id = v_res_id,
      source_line_id = v_line_id
    where t.source_type = 'customer_order_close'
      and t.source_id = v_groups.customer_order_id
      and t.location_type = v_groups.location_type
      and t.location_id = v_groups.location_id
      and t.customer_order_line_id = v_groups.customer_order_line_id
      and t.stock_state in ('reserved', 'free');
  end loop;
end;
$$;

do $$
begin
  if exists (
    select 1 from public.logistics_stock_transaction where source_type = 'reservation_release'
  ) then
    raise exception 'Migration left reservation_release ledger rows';
  end if;
  if exists (
    select 1
    from public.logistics_stock_transaction t
    where t.source_type = 'reservation'
      and not exists (select 1 from public.logistics_reservation r where r.id = t.source_id)
  ) then
    raise exception 'Migration left reservation ledger rows without matching documents';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. Drop legacy tables
-- ---------------------------------------------------------------------------
drop table public.logistics_reservation_release_line_legacy cascade;
drop table public.logistics_reservation_release_legacy cascade;
drop table public.logistics_reservation_line_legacy cascade;
drop table public.logistics_reservation_legacy cascade;

-- ---------------------------------------------------------------------------
-- 7. RPCs
-- ---------------------------------------------------------------------------
drop function if exists public.logistics_post_release(bigint);
drop function if exists public.logistics_post_reservation(bigint);

create or replace function public.logistics_post_reservation(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.logistics_reservation%rowtype;
  v_line public.logistics_reservation_line%rowtype;
  v_order_line public.logistics_customer_order_line%rowtype;
  v_op text := 'reservation:' || p_id || ':post';
  v_open numeric;
  v_product_id bigint;
begin
  select * into strict v_doc from public.logistics_reservation where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.location_type not in ('warehouse', 'production_order_line', 'transfer') then
    raise exception 'Reservation location type % is not allowed', v_doc.location_type;
  end if;
  if v_doc.operation not in ('reserve', 'release') then
    raise exception 'Unknown reservation operation %', v_doc.operation;
  end if;
  if not exists (select 1 from public.logistics_reservation_line where reservation_id = p_id) then
    raise exception 'Reservation % has no lines', p_id;
  end if;

  for v_line in
    select * from public.logistics_reservation_line where reservation_id = p_id order by id
  loop
    select * into strict v_order_line
    from public.logistics_customer_order_line
    where id = v_line.customer_order_line_id;
    if v_order_line.order_id <> v_doc.customer_order_id then
      raise exception 'Reservation line must belong to the customer order';
    end if;
    v_product_id := v_order_line.product_id;

    if v_doc.operation = 'reserve' then
      v_open := v_order_line.quantity
        - public.logistics_shipped_for_line(v_line.customer_order_line_id)
        - public.logistics_reserved_for_line(v_line.customer_order_line_id);
      if v_line.quantity > v_open then
        raise exception 'Cannot reserve more than the open customer order quantity';
      end if;
      perform public.logistics_move(
        v_product_id, v_line.quantity,
        v_doc.location_type, v_doc.location_id, v_doc.location_type, v_doc.location_id,
        'free', 'reserved', null, null, v_doc.customer_order_id, v_line.customer_order_line_id,
        'reservation', p_id, v_line.id, v_op, v_op || ':' || v_line.id
      );
    else
      perform public.logistics_move(
        v_product_id, v_line.quantity,
        v_doc.location_type, v_doc.location_id, v_doc.location_type, v_doc.location_id,
        'reserved', 'free', v_doc.customer_order_id, v_line.customer_order_line_id, null, null,
        'reservation', p_id, v_line.id, v_op, v_op || ':' || v_line.id
      );
    end if;
  end loop;

  update public.logistics_reservation
  set status = 'posted', posted_at = coalesce(posted_at, now())
  where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.logistics_close_customer_order(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_loc record;
  v_line record;
  v_res_id bigint;
begin
  if exists (select 1 from public.logistics_customer_order where id = p_id and status = 'closed') then
    return 'closed';
  end if;

  for v_loc in
    select location_type, location_id
    from public.logistics_stock_transaction
    where stock_state = 'reserved' and customer_order_id = p_id
    group by 1, 2
    having sum(quantity) > 0
    order by 1, 2
  loop
    insert into public.logistics_reservation (
      customer_order_id, location_type, location_id, operation, status, origin, note
    ) values (
      p_id, v_loc.location_type, v_loc.location_id, 'release', 'draft', 'order_close', 'Order closed'
    )
    returning id into v_res_id;

    for v_line in
      select customer_order_line_id, sum(quantity) as qty
      from public.logistics_stock_transaction
      where stock_state = 'reserved'
        and customer_order_id = p_id
        and location_type = v_loc.location_type
        and location_id = v_loc.location_id
      group by 1
      having sum(quantity) > 0
      order by 1
    loop
      insert into public.logistics_reservation_line (
        reservation_id, customer_order_line_id, quantity
      ) values (
        v_res_id, v_line.customer_order_line_id, v_line.qty
      );
    end loop;

    perform public.logistics_post_reservation(v_res_id);
  end loop;

  update public.logistics_customer_order
  set status = 'closed', closed_at = now()
  where id = p_id;
  return 'closed';
end;
$$;

create or replace function public.logistics_cancel_document(p_kind text, p_id bigint)
returns text
language plpgsql
as $$
begin
  if p_kind in ('reservation', 'reservation_release') then
    raise exception 'Posted reservations cannot be cancelled. Create a Reservation with operation=release instead.';
  elsif p_kind = 'shipment' then
    if exists (select 1 from public.logistics_shipment where id = p_id and status = 'posted') then
      perform public.logistics_reverse_source('shipment', p_id);
    end if;
    update public.logistics_shipment set status = 'cancelled', cancelled_at = now() where id = p_id;
  elsif p_kind = 'shipment_return' then
    if exists (select 1 from public.logistics_return where id = p_id and status = 'posted') then
      perform public.logistics_reverse_source('shipment_return', p_id);
    end if;
    update public.logistics_return set status = 'cancelled', cancelled_at = now() where id = p_id;
  elsif p_kind = 'production_output' then
    if exists (select 1 from public.logistics_output where id = p_id and status = 'done') then
      perform public.logistics_reverse_source('production_output', p_id);
    end if;
    update public.logistics_output set status = 'cancelled', cancelled_at = now() where id = p_id;
  elsif p_kind = 'transfer' then
    if exists (select 1 from public.logistics_transfer where id = p_id and status = 'delivered') then
      raise exception 'Delivered transfers are kept as history';
    end if;
    if exists (select 1 from public.logistics_transfer where id = p_id and status = 'sent') then
      perform public.logistics_reverse_source('transfer_send', p_id);
    end if;
    update public.logistics_transfer set status = 'cancelled', cancelled_at = now() where id = p_id;
  else
    raise exception 'Unknown document kind %', p_kind;
  end if;
  return 'cancelled';
end;
$$;

grant execute on function public.logistics_post_reservation(bigint) to anon, authenticated, service_role;
grant execute on function public.logistics_close_customer_order(bigint) to anon, authenticated, service_role;
grant execute on function public.logistics_cancel_document(text, bigint) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 8. Code helper: drop REL prefixes
-- ---------------------------------------------------------------------------
create or replace function public.logistics_code(p_kind text, p_id bigint)
returns text
language sql
immutable
as $$
  select case p_kind
    when 'product' then 'PRD-' || p_id
    when 'manufacturer' then 'PLT-' || p_id
    when 'warehouse' then 'WH-' || p_id
    when 'customer_order' then 'OMS-' || p_id
    when 'production_order' then 'PO-' || p_id
    when 'reservation' then 'RSV-' || p_id
    when 'transfer' then 'TR-' || p_id
    when 'shipment' then 'SHP-' || p_id
    when 'output' then 'OUT-' || p_id
    when 'return' then 'RET-' || p_id
    when 'customer_order_line' then 'COL-' || p_id
    when 'production_order_line' then 'POL-' || p_id
    when 'reservation_line' then 'RSVL-' || p_id
    when 'transfer_line' then 'TRL-' || p_id
    when 'transfer_allocation' then 'TRA-' || p_id
    when 'shipment_line' then 'SHL-' || p_id
    when 'output_line' then 'OUTL-' || p_id
    when 'output_allocation' then 'OUA-' || p_id
    when 'return_line' then 'RETL-' || p_id
    when 'product_manufacturer' then 'PM-' || p_id
    when 'stock_transaction' then 'TXN-' || p_id
    when 'setting' then 'SET-' || p_id
    else p_kind || '-' || p_id
  end;
$$;

update public.logistics_setting
set code_prefixes = (code_prefixes - 'reservationRelease' - 'reservationReleaseLine')
where code_prefixes ? 'reservationRelease'
   or code_prefixes ? 'reservationReleaseLine';

-- ---------------------------------------------------------------------------
-- 9. Validate balances unchanged
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from (
      select * from logistics_balance_before
      except
      select
        product_id, location_type, location_id, stock_state,
        customer_order_id, customer_order_line_id, quantity
      from public.logistics_stock_balance
    ) missing
  ) or exists (
    select 1 from (
      select
        product_id, location_type, location_id, stock_state,
        customer_order_id, customer_order_line_id, quantity
      from public.logistics_stock_balance
      except
      select * from logistics_balance_before
    ) extra
  ) then
    raise exception 'Unified reservation migration changed stock balances';
  end if;
end;
$$;

drop table logistics_balance_before;
drop table logistics_rsv_line_map;
drop table logistics_rsv_doc_map;

commit;
