-- Generic stock owner: order | region | NULL(free). Reservation is source→target.
-- Replaces customer_order_id / customer_order_line_id claims across ledger and documents.

begin;

-- ---------------------------------------------------------------------------
-- 0. Snapshot location+product totals (must match after cutover)
-- ---------------------------------------------------------------------------
create table public.store_owner_balance_before as
select product_id, location_type, location_id, stock_state, sum(quantity) as quantity
from public.store_stock_transaction
group by 1, 2, 3, 4
having abs(sum(quantity)) > 0.0000001;

-- ---------------------------------------------------------------------------
-- 1. Region catalog
-- ---------------------------------------------------------------------------
create table public.store_region (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint store_region_name_unique unique (name)
);

comment on table public.store_region is 'Sales/ops region that can own reserved stock.';

insert into public.store_region (name) values
  ('United Arab Emirates'),
  ('Russia'),
  ('Kazakhstan'),
  ('Belarus'),
  ('Uzbekistan'),
  ('Mexico'),
  ('Germany'),
  ('United States'),
  ('India'),
  ('Oman');

alter table public.store_region enable row level security;
create policy store_region_open_all on public.store_region for all using (true) with check (true);
grant select, insert, update, delete on public.store_region to anon, authenticated, service_role;
grant usage, select on sequence public.store_region_id_seq to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 2. Owner pair helpers
-- ---------------------------------------------------------------------------
create or replace function public.store_assert_owner(p_type text, p_id bigint)
returns void
language plpgsql
stable
as $$
begin
  if p_type is null and p_id is null then
    return;
  end if;
  if p_type is null or p_id is null then
    raise exception 'Owner type and id must both be set or both be empty';
  end if;
  if p_type not in ('order', 'region') then
    raise exception 'Owner type must be order or region';
  end if;
  if p_type = 'order' and not exists (select 1 from public.store_customer_order where id = p_id) then
    raise exception 'Unknown customer order %', p_id;
  end if;
  if p_type = 'region' and not exists (select 1 from public.store_region where id = p_id) then
    raise exception 'Unknown region %', p_id;
  end if;
end;
$$;

create or replace function public.store_owners_equal(p_a_type text, p_a_id bigint, p_b_type text, p_b_id bigint)
returns boolean
language sql
immutable
as $$
  select p_a_type is not distinct from p_b_type and p_a_id is not distinct from p_b_id;
$$;

-- ---------------------------------------------------------------------------
-- 3. Add owner columns and backfill
-- ---------------------------------------------------------------------------
alter table public.store_stock_transaction
  add column owner_type text,
  add column owner_id bigint;

update public.store_stock_transaction
set owner_type = case when customer_order_id is null then null else 'order' end,
    owner_id = customer_order_id;

alter table public.store_reservation
  add column to_owner_type text,
  add column to_owner_id bigint;

alter table public.store_reservation disable trigger user;
update public.store_reservation
set to_owner_type = case when operation = 'reserve' then 'order' else null end,
    to_owner_id = case when operation = 'reserve' then customer_order_id else null end;
alter table public.store_reservation enable trigger user;

alter table public.store_reservation_line
  add column product_id bigint references public.store_product (id),
  add column from_owner_type text,
  add column from_owner_id bigint;

alter table public.store_reservation_line disable trigger user;
update public.store_reservation_line l
set product_id = col.product_id,
    from_owner_type = case when r.operation = 'release' then 'order' else null end,
    from_owner_id = case when r.operation = 'release' then r.customer_order_id else null end
from public.store_reservation r,
     public.store_customer_order_line col
where r.id = l.reservation_id
  and col.id = l.customer_order_line_id;
alter table public.store_reservation_line enable trigger user;

alter table public.store_transfer_allocation
  add column owner_type text,
  add column owner_id bigint;

update public.store_transfer_allocation
set owner_type = 'order',
    owner_id = customer_order_id;

alter table public.store_output_allocation
  add column owner_type text,
  add column owner_id bigint;

update public.store_output_allocation
set owner_type = 'order',
    owner_id = customer_order_id;

-- ---------------------------------------------------------------------------
-- 4. Drop dependents that still mention old claim columns
-- ---------------------------------------------------------------------------
drop view if exists public.store_stock_balance;
drop trigger if exists store_reservation_line_guard on public.store_reservation_line;
drop trigger if exists store_reservation_line_guard_trg on public.store_reservation_line;
drop trigger if exists logistics_reservation_line_guard on public.store_reservation_line;

drop function if exists public.store_post_reservation(bigint);
drop function if exists public.store_close_customer_order(bigint);
drop function if exists public.store_close_production_order(bigint);
drop function if exists public.store_post_shipment(bigint);
drop function if exists public.store_post_return(bigint);
drop function if exists public.store_send_transfer(bigint);
drop function if exists public.store_complete_transfer(bigint);
drop function if exists public.store_complete_output(bigint);
drop function if exists public.store_reverse_source(text, bigint);
drop function if exists public.store_sync_production_activation(bigint);
drop function if exists public.store_reservation_line_guard();
drop function if exists public.store_reserved_for_line(bigint);
drop function if exists public.store_shipped_for_line(bigint);
drop function if exists public.store_move(bigint, numeric, text, bigint, text, bigint, text, text, bigint, bigint, bigint, bigint, text, bigint, bigint, text, text);
drop function if exists public.store_write_tx(bigint, numeric, text, bigint, text, bigint, bigint, text, bigint, bigint, text, text, bigint, timestamp with time zone);
drop function if exists public.store_qty(bigint, text, bigint, text, bigint, bigint);
drop function if exists public.store_reset_logistics_stories(bigint, bigint);

-- ---------------------------------------------------------------------------
-- 5. Drop old claim columns and tighten new ones
-- ---------------------------------------------------------------------------
alter table public.store_stock_transaction
  drop column customer_order_id,
  drop column customer_order_line_id;

alter table public.store_reservation
  drop column customer_order_id,
  drop column operation;

alter table public.store_reservation_line
  drop constraint if exists store_reservation_line_unique,
  drop constraint if exists logistics_reservation_line_unique,
  drop column customer_order_line_id;

alter table public.store_reservation_line
  alter column product_id set not null;

alter table public.store_shipment_line
  drop column customer_order_line_id;

alter table public.store_transfer_allocation
  drop column customer_order_id,
  drop column customer_order_line_id,
  alter column owner_type set not null,
  alter column owner_id set not null;

alter table public.store_output_allocation
  drop column customer_order_id,
  drop column customer_order_line_id,
  alter column owner_type set not null,
  alter column owner_id set not null;

alter table public.store_customer_order_line
  add constraint store_customer_order_line_product_unique unique (order_id, product_id);

alter table public.store_stock_transaction
  add constraint store_stock_transaction_owner_pair_chk
    check (
      (owner_type is null and owner_id is null)
      or (owner_type in ('order', 'region') and owner_id is not null)
    ),
  add constraint store_stock_transaction_owner_state_chk
    check (
      (stock_state = 'free' and owner_type is null)
      or (stock_state = 'reserved' and owner_type is not null)
      or (stock_state = 'shipped' and owner_type = 'order')
    );

alter table public.store_reservation
  add constraint store_reservation_to_owner_pair_chk
    check (
      (to_owner_type is null and to_owner_id is null)
      or (to_owner_type in ('order', 'region') and to_owner_id is not null)
    );

alter table public.store_reservation_line
  add constraint store_reservation_line_from_owner_pair_chk
    check (
      (from_owner_type is null and from_owner_id is null)
      or (from_owner_type in ('order', 'region') and from_owner_id is not null)
    );

create unique index store_reservation_line_source_uidx
  on public.store_reservation_line (
    reservation_id,
    product_id,
    coalesce(from_owner_type, ''),
    coalesce(from_owner_id, 0)
  );

alter table public.store_transfer_allocation
  add constraint store_transfer_allocation_owner_pair_chk
    check (owner_type in ('order', 'region') and owner_id is not null);

alter table public.store_output_allocation
  add constraint store_output_allocation_owner_pair_chk
    check (owner_type in ('order', 'region') and owner_id is not null);

create or replace view public.store_stock_balance as
select
  product_id,
  location_type,
  location_id,
  stock_state,
  owner_type,
  owner_id,
  sum(quantity) as quantity
from public.store_stock_transaction
group by product_id, location_type, location_id, stock_state, owner_type, owner_id
having abs(sum(quantity)) > 0.0000001;

grant select on public.store_stock_balance to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Owner triggers
-- ---------------------------------------------------------------------------
create or replace function public.store_owner_row_guard()
returns trigger
language plpgsql
as $$
begin
  if tg_table_name = 'store_reservation' then
    perform public.store_assert_owner(new.to_owner_type, new.to_owner_id);
  elsif tg_table_name = 'store_reservation_line' then
    perform public.store_assert_owner(new.from_owner_type, new.from_owner_id);
  elsif tg_table_name in ('store_stock_transaction', 'store_transfer_allocation', 'store_output_allocation') then
    perform public.store_assert_owner(new.owner_type, new.owner_id);
  end if;
  return new;
end;
$$;

create trigger store_stock_transaction_owner_guard
  before insert or update on public.store_stock_transaction
  for each row execute function public.store_owner_row_guard();

create trigger store_reservation_owner_guard
  before insert or update on public.store_reservation
  for each row execute function public.store_owner_row_guard();

create trigger store_reservation_line_owner_guard
  before insert or update on public.store_reservation_line
  for each row execute function public.store_owner_row_guard();

create trigger store_transfer_allocation_owner_guard
  before insert or update on public.store_transfer_allocation
  for each row execute function public.store_owner_row_guard();

create trigger store_output_allocation_owner_guard
  before insert or update on public.store_output_allocation
  for each row execute function public.store_owner_row_guard();

create or replace function public.store_reservation_line_guard()
returns trigger
language plpgsql
as $$
declare
  v_doc public.store_reservation%rowtype;
begin
  if tg_op = 'DELETE' then
    select * into strict v_doc from public.store_reservation where id = old.reservation_id;
    if v_doc.status = 'posted' then
      raise exception 'Posted reservations are immutable';
    end if;
    return old;
  end if;

  select * into strict v_doc from public.store_reservation where id = new.reservation_id;
  if v_doc.status = 'posted' then
    raise exception 'Posted reservations are immutable';
  end if;
  if new.quantity <= 0 then
    raise exception 'Quantity must be positive';
  end if;
  if public.store_owners_equal(new.from_owner_type, new.from_owner_id, v_doc.to_owner_type, v_doc.to_owner_id) then
    raise exception 'Reservation cannot move quantity to the same owner';
  end if;
  if v_doc.to_owner_type is null and new.from_owner_type is null then
    raise exception 'Reservation cannot move free to free';
  end if;
  perform public.store_assert_owner(new.from_owner_type, new.from_owner_id);
  return new;
end;
$$;

drop trigger if exists store_reservation_line_guard on public.store_reservation_line;
drop trigger if exists logistics_reservation_line_guard on public.store_reservation_line;
create trigger store_reservation_line_guard
  before insert or update or delete on public.store_reservation_line
  for each row execute function public.store_reservation_line_guard();

-- ---------------------------------------------------------------------------
-- 7. Ledger primitives
-- ---------------------------------------------------------------------------
create or replace function public.store_qty(
  p_product_id bigint,
  p_location_type text,
  p_location_id bigint,
  p_stock_state text,
  p_owner_type text,
  p_owner_id bigint
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(quantity), 0)
  from public.store_stock_transaction
  where product_id = p_product_id
    and location_type = p_location_type
    and location_id = p_location_id
    and stock_state = p_stock_state
    and owner_type is not distinct from p_owner_type
    and owner_id is not distinct from p_owner_id;
$$;

create or replace function public.store_reserved_for_owner_product(
  p_owner_type text,
  p_owner_id bigint,
  p_product_id bigint
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(quantity), 0)
  from public.store_stock_transaction
  where stock_state = 'reserved'
    and owner_type is not distinct from p_owner_type
    and owner_id is not distinct from p_owner_id
    and product_id = p_product_id;
$$;

create or replace function public.store_shipped_for_owner_product(
  p_owner_type text,
  p_owner_id bigint,
  p_product_id bigint
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(quantity), 0)
  from public.store_stock_transaction
  where stock_state = 'shipped'
    and owner_type is not distinct from p_owner_type
    and owner_id is not distinct from p_owner_id
    and product_id = p_product_id;
$$;

create or replace function public.store_write_tx(
  p_product_id bigint,
  p_quantity numeric,
  p_location_type text,
  p_location_id bigint,
  p_stock_state text,
  p_owner_type text,
  p_owner_id bigint,
  p_source_type text,
  p_source_id bigint,
  p_source_line_id bigint,
  p_operation_id text,
  p_idempotency_key text,
  p_reverses_transaction_id bigint default null,
  p_occurred_at timestamptz default now()
)
returns bigint
language plpgsql
as $$
declare
  v_existing bigint;
  v_id bigint;
  v_unit text;
begin
  perform public.store_assert_owner(p_owner_type, p_owner_id);

  select transaction_id into v_existing
  from public.store_stock_transaction
  where idempotency_key = p_idempotency_key;
  if v_existing is not null then
    return v_existing;
  end if;

  select unit into v_unit from public.store_product where id = p_product_id;
  if v_unit is null then
    raise exception 'Unknown product %', p_product_id;
  end if;

  insert into public.store_stock_transaction (
    occurred_at, posted_at, product_id, unit, quantity,
    location_type, location_id, stock_state, owner_type, owner_id,
    source_type, source_id, source_line_id, operation_id, idempotency_key, reverses_transaction_id
  ) values (
    p_occurred_at, now(), p_product_id, v_unit, p_quantity,
    p_location_type, p_location_id, p_stock_state, p_owner_type, p_owner_id,
    p_source_type, p_source_id, p_source_line_id, p_operation_id, p_idempotency_key, p_reverses_transaction_id
  ) returning transaction_id into v_id;
  return v_id;
end;
$$;

create or replace function public.store_move(
  p_product_id bigint,
  p_quantity numeric,
  p_from_type text,
  p_from_id bigint,
  p_to_type text,
  p_to_id bigint,
  p_from_state text,
  p_to_state text,
  p_from_owner_type text,
  p_from_owner_id bigint,
  p_to_owner_type text,
  p_to_owner_id bigint,
  p_source_type text,
  p_source_id bigint,
  p_source_line_id bigint,
  p_operation_id text,
  p_key_prefix text
)
returns void
language plpgsql
as $$
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be positive';
  end if;
  if public.store_qty(
    p_product_id, p_from_type, p_from_id, p_from_state, p_from_owner_type, p_from_owner_id
  ) < p_quantity then
    raise exception 'Not enough stock for % %', p_from_state, p_product_id;
  end if;

  perform public.store_write_tx(
    p_product_id, -p_quantity, p_from_type, p_from_id, p_from_state,
    p_from_owner_type, p_from_owner_id, p_source_type, p_source_id, p_source_line_id,
    p_operation_id, p_key_prefix || ':minus'
  );
  perform public.store_write_tx(
    p_product_id, p_quantity, p_to_type, p_to_id, p_to_state,
    p_to_owner_type, p_to_owner_id, p_source_type, p_source_id, p_source_line_id,
    p_operation_id, p_key_prefix || ':plus'
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 8. Posting RPCs
-- ---------------------------------------------------------------------------
create or replace function public.store_post_reservation(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_reservation%rowtype;
  v_line public.store_reservation_line%rowtype;
  v_order_line public.store_customer_order_line%rowtype;
  v_op text := 'reservation:' || p_id || ':post';
  v_open numeric;
  v_from_state text;
  v_to_state text;
begin
  select * into strict v_doc from public.store_reservation where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.location_type not in ('warehouse', 'production_order_line', 'transfer') then
    raise exception 'Reservation location type % is not allowed', v_doc.location_type;
  end if;
  if not exists (select 1 from public.store_reservation_line where reservation_id = p_id) then
    raise exception 'Reservation % has no lines', p_id;
  end if;
  perform public.store_assert_owner(v_doc.to_owner_type, v_doc.to_owner_id);

  for v_line in
    select * from public.store_reservation_line where reservation_id = p_id order by id
  loop
    if public.store_owners_equal(
      v_line.from_owner_type, v_line.from_owner_id, v_doc.to_owner_type, v_doc.to_owner_id
    ) then
      raise exception 'Reservation cannot move quantity to the same owner';
    end if;
    if v_doc.to_owner_type is null and v_line.from_owner_type is null then
      raise exception 'Reservation cannot move free to free';
    end if;

    if v_doc.to_owner_type = 'order' then
      select * into v_order_line
      from public.store_customer_order_line
      where order_id = v_doc.to_owner_id and product_id = v_line.product_id;
      if v_order_line.id is null then
        raise exception 'Customer order does not contain this product';
      end if;
      v_open := v_order_line.quantity
        - public.store_shipped_for_owner_product('order', v_doc.to_owner_id, v_line.product_id)
        - public.store_reserved_for_owner_product('order', v_doc.to_owner_id, v_line.product_id);
      if v_line.quantity > v_open then
        raise exception 'Cannot reserve more than the open customer order quantity';
      end if;
    end if;

    v_from_state := case when v_line.from_owner_type is null then 'free' else 'reserved' end;
    v_to_state := case when v_doc.to_owner_type is null then 'free' else 'reserved' end;

    perform public.store_move(
      v_line.product_id, v_line.quantity,
      v_doc.location_type, v_doc.location_id, v_doc.location_type, v_doc.location_id,
      v_from_state, v_to_state,
      v_line.from_owner_type, v_line.from_owner_id,
      v_doc.to_owner_type, v_doc.to_owner_id,
      'reservation', p_id, v_line.id, v_op, v_op || ':' || v_line.id
    );
  end loop;

  update public.store_reservation
  set status = 'posted', posted_at = coalesce(posted_at, now())
  where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.store_close_customer_order(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_loc record;
  v_line record;
  v_res_id bigint;
begin
  if exists (select 1 from public.store_customer_order where id = p_id and status = 'closed') then
    return 'closed';
  end if;

  for v_loc in
    select location_type, location_id
    from public.store_stock_transaction
    where stock_state = 'reserved' and owner_type = 'order' and owner_id = p_id
    group by 1, 2
    having sum(quantity) > 0
    order by 1, 2
  loop
    insert into public.store_reservation (
      location_type, location_id, to_owner_type, to_owner_id, status, origin, note
    ) values (
      v_loc.location_type, v_loc.location_id, null, null, 'draft', 'order_close', 'Order closed'
    )
    returning id into v_res_id;

    for v_line in
      select product_id, sum(quantity) as qty
      from public.store_stock_transaction
      where stock_state = 'reserved'
        and owner_type = 'order'
        and owner_id = p_id
        and location_type = v_loc.location_type
        and location_id = v_loc.location_id
      group by 1
      having sum(quantity) > 0
      order by 1
    loop
      insert into public.store_reservation_line (
        reservation_id, product_id, quantity, from_owner_type, from_owner_id
      ) values (
        v_res_id, v_line.product_id, v_line.qty, 'order', p_id
      );
    end loop;

    perform public.store_post_reservation(v_res_id);
  end loop;

  update public.store_customer_order
  set status = 'closed', closed_at = now()
  where id = p_id;
  return 'closed';
end;
$$;

create or replace function public.store_close_production_order(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_hold record;
  v_line record;
  v_res_id bigint;
  r record;
  v_op text := 'production_close:' || p_id;
begin
  if exists (select 1 from public.store_production_order where id = p_id and status = 'closed') then
    return 'closed';
  end if;

  for v_hold in
    select owner_type, owner_id, location_id
    from public.store_stock_transaction
    where stock_state = 'reserved'
      and location_type = 'production_order_line'
      and location_id in (select id from public.store_production_order_line where order_id = p_id)
      and owner_type is not null
    group by 1, 2, 3
    having sum(quantity) > 0
    order by 1, 2, 3
  loop
    insert into public.store_reservation (
      location_type, location_id, to_owner_type, to_owner_id, status, origin, note
    ) values (
      'production_order_line', v_hold.location_id, null, null, 'draft', 'order_close', 'Production order closed'
    )
    returning id into v_res_id;

    for v_line in
      select product_id, sum(quantity) as qty
      from public.store_stock_transaction
      where stock_state = 'reserved'
        and owner_type is not distinct from v_hold.owner_type
        and owner_id is not distinct from v_hold.owner_id
        and location_type = 'production_order_line'
        and location_id = v_hold.location_id
      group by 1
      having sum(quantity) > 0
      order by 1
    loop
      insert into public.store_reservation_line (
        reservation_id, product_id, quantity, from_owner_type, from_owner_id
      ) values (
        v_res_id, v_line.product_id, v_line.qty, v_hold.owner_type, v_hold.owner_id
      );
    end loop;

    perform public.store_post_reservation(v_res_id);
  end loop;

  if exists (
    select 1
    from public.store_stock_transaction
    where stock_state = 'reserved'
      and location_type = 'production_order_line'
      and location_id in (select id from public.store_production_order_line where order_id = p_id)
    group by product_id, location_id, owner_type, owner_id
    having sum(quantity) > 0
  ) then
    raise exception 'Cannot close a production order while reserved quantity remains';
  end if;

  for r in
    select product_id, location_id, stock_state, owner_type, owner_id, sum(quantity) as qty
    from public.store_stock_transaction
    where location_type = 'production_order_line'
      and location_id in (select id from public.store_production_order_line where order_id = p_id)
      and stock_state = 'free'
    group by 1, 2, 3, 4, 5
    having sum(quantity) > 0
  loop
    perform public.store_write_tx(
      r.product_id, -r.qty, 'production_order_line', r.location_id, r.stock_state,
      r.owner_type, r.owner_id,
      'production_close', p_id, r.location_id, v_op,
      v_op || ':' || r.location_id || ':' || r.stock_state || ':' || coalesce(r.owner_id::text, 'free')
    );
  end loop;

  update public.store_production_order
  set status = 'closed', closed_at = now()
  where id = p_id;
  return 'closed';
end;
$$;

create or replace function public.store_post_shipment(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_shipment%rowtype;
  v_line public.store_shipment_line%rowtype;
  v_order_line public.store_customer_order_line%rowtype;
  v_op text := 'shipment:' || p_id || ':post';
  v_shipped numeric;
begin
  select * into strict v_doc from public.store_shipment where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled documents cannot be posted';
  end if;

  for v_line in select * from public.store_shipment_line where shipment_id = p_id
  loop
    select * into v_order_line
    from public.store_customer_order_line
    where order_id = v_doc.customer_order_id and product_id = v_line.product_id;
    if v_order_line.id is null then
      raise exception 'Shipment line must match the single customer order';
    end if;
    v_shipped := public.store_shipped_for_owner_product('order', v_doc.customer_order_id, v_line.product_id);
    if v_shipped + v_line.quantity > v_order_line.quantity then
      raise exception 'Cannot ship more than the ordered quantity';
    end if;
    perform public.store_move(
      v_line.product_id, v_line.quantity,
      'warehouse', v_doc.warehouse_id, 'customer_order', v_doc.customer_order_id,
      'reserved', 'shipped',
      'order', v_doc.customer_order_id,
      'order', v_doc.customer_order_id,
      'shipment', p_id, v_line.id, v_op, v_op || ':' || v_line.id
    );
  end loop;

  update public.store_shipment
  set status = 'posted', posted_at = now()
  where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.store_post_return(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_return%rowtype;
  v_ship public.store_shipment%rowtype;
  v_line public.store_return_line%rowtype;
  v_ship_line public.store_shipment_line%rowtype;
  v_already numeric;
  v_op text := 'shipment_return:' || p_id || ':post';
begin
  select * into strict v_doc from public.store_return where id = p_id;
  if v_doc.status = 'posted' then
    return 'posted';
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled documents cannot be posted';
  end if;
  select * into strict v_ship from public.store_shipment where id = v_doc.shipment_id;
  if v_ship.status <> 'posted' then
    raise exception 'Return requires a posted shipment';
  end if;

  for v_line in select * from public.store_return_line where return_id = p_id
  loop
    select * into strict v_ship_line from public.store_shipment_line where id = v_line.shipment_line_id;
    select coalesce(sum(rl.quantity), 0) into v_already
    from public.store_return_line rl
    join public.store_return r on r.id = rl.return_id
    where rl.shipment_line_id = v_line.shipment_line_id
      and r.status = 'posted'
      and r.id <> p_id;
    if v_already + v_line.quantity > v_ship_line.quantity then
      raise exception 'Return cannot exceed the shipped quantity';
    end if;
    perform public.store_move(
      v_ship_line.product_id, v_line.quantity,
      'customer_order', v_ship.customer_order_id, 'warehouse', v_ship.warehouse_id,
      'shipped', 'free',
      'order', v_ship.customer_order_id,
      null, null,
      'shipment_return', p_id, v_line.id, v_op, v_op || ':' || v_line.id
    );
  end loop;

  update public.store_return
  set status = 'posted', posted_at = now()
  where id = p_id;
  return 'posted';
end;
$$;

create or replace function public.store_send_transfer(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_transfer%rowtype;
  v_line public.store_transfer_line%rowtype;
  v_alloc public.store_transfer_allocation%rowtype;
  v_allocated numeric;
  v_free numeric;
  v_op text := 'transfer_send:' || p_id;
begin
  select * into strict v_doc from public.store_transfer where id = p_id;
  if v_doc.status in ('sent', 'delivered') then
    return v_doc.status;
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled documents cannot be posted';
  end if;

  for v_line in select * from public.store_transfer_line where transfer_id = p_id
  loop
    select coalesce(sum(quantity), 0) into v_allocated
    from public.store_transfer_allocation
    where line_id = v_line.id;
    if v_allocated > v_line.quantity then
      raise exception 'Allocated quantity cannot exceed the document line';
    end if;
    v_free := v_line.quantity - v_allocated;

    for v_alloc in select * from public.store_transfer_allocation where line_id = v_line.id
    loop
      perform public.store_assert_owner(v_alloc.owner_type, v_alloc.owner_id);
      perform public.store_move(
        v_line.product_id, v_alloc.quantity,
        'warehouse', v_doc.from_warehouse_id, 'transfer', p_id,
        'reserved', 'reserved',
        v_alloc.owner_type, v_alloc.owner_id,
        v_alloc.owner_type, v_alloc.owner_id,
        'transfer_send', p_id, v_line.id, v_op, v_op || ':alloc:' || v_alloc.id
      );
    end loop;

    if v_free > 0 then
      perform public.store_move(
        v_line.product_id, v_free,
        'warehouse', v_doc.from_warehouse_id, 'transfer', p_id,
        'free', 'free', null, null, null, null,
        'transfer_send', p_id, v_line.id, v_op, v_op || ':free:' || v_line.id
      );
    end if;
  end loop;

  update public.store_transfer
  set status = 'sent', sent_at = now()
  where id = p_id;
  return 'sent';
end;
$$;

create or replace function public.store_complete_transfer(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_transfer%rowtype;
  r record;
  v_line_id bigint;
  v_op text := 'transfer_complete:' || p_id;
begin
  select * into strict v_doc from public.store_transfer where id = p_id;
  if v_doc.status = 'delivered' then
    return 'delivered';
  end if;
  if v_doc.status <> 'sent' then
    raise exception 'Transfer must be sent before it can be delivered';
  end if;

  for r in
    select product_id, stock_state, owner_type, owner_id, sum(quantity) as qty
    from public.store_stock_transaction
    where location_type = 'transfer' and location_id = p_id
    group by 1, 2, 3, 4
    having sum(quantity) > 0
  loop
    select id into v_line_id
    from public.store_transfer_line
    where transfer_id = p_id and product_id = r.product_id
    limit 1;

    perform public.store_move(
      r.product_id, r.qty,
      'transfer', p_id, 'warehouse', v_doc.to_warehouse_id,
      r.stock_state, r.stock_state,
      r.owner_type, r.owner_id,
      r.owner_type, r.owner_id,
      'transfer_complete', p_id, v_line_id, v_op,
      v_op || ':' || r.product_id || ':' || r.stock_state || ':' || coalesce(r.owner_id::text, 'free')
    );
  end loop;

  update public.store_transfer
  set status = 'delivered'
  where id = p_id;
  return 'delivered';
end;
$$;

create or replace function public.store_complete_output(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_doc public.store_output%rowtype;
  v_order public.store_production_order%rowtype;
  v_mfr public.store_manufacturer%rowtype;
  v_line public.store_output_line%rowtype;
  v_prod_line public.store_production_order_line%rowtype;
  v_already numeric;
  v_remain numeric;
  v_take numeric;
  r record;
  v_op text := 'production_output:' || p_id || ':complete';
begin
  select * into strict v_doc from public.store_output where id = p_id;
  if v_doc.status = 'done' then
    return 'done';
  end if;
  if v_doc.status = 'cancelled' then
    raise exception 'Cancelled outputs cannot be completed';
  end if;
  if exists (
    select 1 from public.store_stock_transaction
    where source_type = 'production_output' and source_id = p_id
  ) then
    update public.store_output
    set status = 'done', done_at = coalesce(done_at, now())
    where id = p_id;
    return 'done';
  end if;
  select * into strict v_order from public.store_production_order where id = v_doc.production_order_id;
  if v_order.status in ('closed', 'cancelled') then
    raise exception 'Cannot output from a closed production order';
  end if;
  select * into strict v_mfr from public.store_manufacturer where id = v_order.manufacturer_id;

  for v_line in select * from public.store_output_line where output_id = p_id
  loop
    select * into strict v_prod_line
    from public.store_production_order_line
    where id = v_line.production_order_line_id;
    if v_prod_line.product_id <> v_line.product_id then
      raise exception 'Output product must match the production order line';
    end if;
    select coalesce(sum(ol.quantity), 0) into v_already
    from public.store_output_line ol
    join public.store_output o on o.id = ol.output_id
    where ol.production_order_line_id = v_line.production_order_line_id
      and o.status = 'done';
    if v_already + v_line.quantity > v_prod_line.quantity then
      raise exception 'Cannot output more than the production order line';
    end if;

    v_remain := v_line.quantity;

    for r in
      select owner_type, owner_id, sum(quantity) as qty
      from public.store_stock_transaction
      where location_type = 'production_order_line'
        and location_id = v_prod_line.id
        and product_id = v_line.product_id
        and stock_state = 'reserved'
      group by 1, 2
      having sum(quantity) > 0
      order by owner_type, owner_id
    loop
      exit when v_remain <= 0;
      v_take := least(r.qty, v_remain);
      perform public.store_move(
        v_line.product_id, v_take,
        'production_order_line', v_prod_line.id, 'warehouse', v_mfr.warehouse_id,
        'reserved', 'reserved',
        r.owner_type, r.owner_id,
        r.owner_type, r.owner_id,
        'production_output', p_id, v_line.id, v_op,
        v_op || ':rsv:' || coalesce(r.owner_type, 'none') || ':' || coalesce(r.owner_id::text, 'none')
      );
      v_remain := v_remain - v_take;
    end loop;

    if v_remain > 0 then
      perform public.store_move(
        v_line.product_id, v_remain,
        'production_order_line', v_prod_line.id, 'warehouse', v_mfr.warehouse_id,
        'free', 'free', null, null, null, null,
        'production_output', p_id, v_line.id, v_op, v_op || ':free:' || v_line.id
      );
    end if;
  end loop;

  update public.store_output
  set status = 'done', done_at = now()
  where id = p_id;
  return 'done';
end;
$$;

create or replace function public.store_reverse_source(p_source_type text, p_source_id bigint)
returns void
language plpgsql
as $$
declare
  r record;
  v_op text := p_source_type || ':' || p_source_id || ':cancel';
begin
  for r in
    select *
    from public.store_stock_transaction
    where source_type = p_source_type
      and source_id = p_source_id
      and reverses_transaction_id is null
      and transaction_id not in (
        select reverses_transaction_id
        from public.store_stock_transaction
        where reverses_transaction_id is not null
      )
    order by posted_at, transaction_id
  loop
    perform public.store_write_tx(
      r.product_id, -r.quantity, r.location_type, r.location_id, r.stock_state,
      r.owner_type, r.owner_id, r.source_type, r.source_id, r.source_line_id,
      v_op, r.idempotency_key || ':rev', r.transaction_id
    );
  end loop;
end;
$$;

create or replace function public.store_sync_production_activation(p_id bigint)
returns text
language plpgsql
as $$
declare
  v_order public.store_production_order%rowtype;
  v_line public.store_production_order_line%rowtype;
  v_delta numeric;
  v_op text := 'production_activation:' || p_id || ':sync';
begin
  select * into strict v_order from public.store_production_order where id = p_id;
  if v_order.status in ('cancelled', 'closed') then
    return v_order.status;
  end if;

  for v_line in select * from public.store_production_order_line where order_id = p_id
  loop
    v_delta := v_line.quantity - v_line.activated_quantity;
    if v_delta > 0 then
      perform public.store_write_tx(
        v_line.product_id, v_delta, 'production_order_line', v_line.id, 'free',
        null, null, 'production_activation', p_id, v_line.id,
        v_op, v_op || ':' || v_line.id || ':' || (v_line.activated_quantity + v_delta)::text
      );
      update public.store_production_order_line
      set activated_quantity = activated_quantity + v_delta
      where id = v_line.id;
    elsif v_delta < 0 then
      if public.store_qty(
        v_line.product_id, 'production_order_line', v_line.id, 'free', null, null
      ) < -v_delta then
        raise exception 'Not enough unused production quantity to reduce the line';
      end if;
      perform public.store_write_tx(
        v_line.product_id, v_delta, 'production_order_line', v_line.id, 'free',
        null, null, 'production_activation', p_id, v_line.id,
        v_op, v_op || ':' || v_line.id || ':down:' || v_line.quantity::text
      );
      update public.store_production_order_line
      set activated_quantity = v_line.quantity
      where id = v_line.id;
    end if;
  end loop;
  return v_order.status;
end;
$$;

create or replace function public.store_cancel_document(p_kind text, p_id bigint)
returns text
language plpgsql
as $$
begin
  if p_kind in ('reservation', 'reservation_release') then
    raise exception 'Posted reservations cannot be cancelled. Create a Reservation that releases to Free instead.';
  elsif p_kind = 'shipment' then
    if exists (select 1 from public.store_shipment where id = p_id and status = 'posted') then
      perform public.store_reverse_source('shipment', p_id);
    end if;
    update public.store_shipment set status = 'cancelled', cancelled_at = now() where id = p_id;
  elsif p_kind = 'shipment_return' then
    if exists (select 1 from public.store_return where id = p_id and status = 'posted') then
      perform public.store_reverse_source('shipment_return', p_id);
    end if;
    update public.store_return set status = 'cancelled', cancelled_at = now() where id = p_id;
  elsif p_kind = 'production_output' then
    if exists (select 1 from public.store_output where id = p_id and status = 'done') then
      perform public.store_reverse_source('production_output', p_id);
    end if;
    update public.store_output set status = 'cancelled', cancelled_at = now() where id = p_id;
  elsif p_kind = 'transfer' then
    if exists (select 1 from public.store_transfer where id = p_id and status = 'delivered') then
      raise exception 'Delivered transfers are kept as history';
    end if;
    if exists (select 1 from public.store_transfer where id = p_id and status = 'sent') then
      perform public.store_reverse_source('transfer_send', p_id);
    end if;
    update public.store_transfer set status = 'cancelled', cancelled_at = now() where id = p_id;
  else
    raise exception 'Unknown document kind %', p_kind;
  end if;
  return 'cancelled';
end;
$$;

-- ---------------------------------------------------------------------------
-- 9. Codes
-- ---------------------------------------------------------------------------
create or replace function public.store_code_kind_key(p_kind text)
returns text
language sql
immutable
as $$
  select case p_kind
    when 'customer_order' then 'customerOrder'
    when 'production_order' then 'productionOrder'
    when 'reservation_release' then 'reservationRelease'
    when 'customer_order_line' then 'customerOrderLine'
    when 'production_order_line' then 'productionOrderLine'
    when 'reservation_line' then 'reservationLine'
    when 'reservation_release_line' then 'reservationReleaseLine'
    when 'transfer_line' then 'transferLine'
    when 'transfer_allocation' then 'transferAllocation'
    when 'shipment_line' then 'shipmentLine'
    when 'output_line' then 'outputLine'
    when 'output_allocation' then 'outputAllocation'
    when 'return_line' then 'returnLine'
    when 'stock_transaction' then 'stockTransaction'
    else p_kind
  end;
$$;

create or replace function public.store_code(p_kind text, p_id bigint)
returns text
language sql
stable
as $$
  select coalesce(
    nullif(
      (
        select s.code_prefixes ->> public.store_code_kind_key(p_kind)
        from public.store_setting s
        order by s.id
        limit 1
      ),
      ''
    ),
    case p_kind
      when 'product' then 'PRD'
      when 'manufacturer' then 'PLT'
      when 'warehouse' then 'WH'
      when 'region' then 'REG'
      when 'customer_order' then 'OMS'
      when 'production_order' then 'PO'
      when 'reservation' then 'RSV'
      when 'reservation_release' then 'REL'
      when 'transfer' then 'TR'
      when 'shipment' then 'SHP'
      when 'output' then 'OUT'
      when 'return' then 'RET'
      when 'customer_order_line' then 'COL'
      when 'production_order_line' then 'POL'
      when 'reservation_line' then 'RSVL'
      when 'reservation_release_line' then 'RELL'
      when 'transfer_line' then 'TRL'
      when 'transfer_allocation' then 'TRA'
      when 'shipment_line' then 'SHL'
      when 'output_line' then 'OUTL'
      when 'output_allocation' then 'OUA'
      when 'return_line' then 'RETL'
      when 'stock_transaction' then 'TXN'
      when 'setting' then 'SET'
      else p_kind
    end
  ) || '-' || p_id::text;
$$;

grant execute on function public.store_assert_owner(text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_owners_equal(text, bigint, text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_qty(bigint, text, bigint, text, text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_reserved_for_owner_product(text, bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.store_shipped_for_owner_product(text, bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.store_write_tx(bigint, numeric, text, bigint, text, text, bigint, text, bigint, bigint, text, text, bigint, timestamptz) to anon, authenticated, service_role;
grant execute on function public.store_move(bigint, numeric, text, bigint, text, bigint, text, text, text, bigint, text, bigint, text, bigint, bigint, text, text) to anon, authenticated, service_role;
grant execute on function public.store_post_reservation(bigint) to anon, authenticated, service_role;
grant execute on function public.store_close_customer_order(bigint) to anon, authenticated, service_role;
grant execute on function public.store_close_production_order(bigint) to anon, authenticated, service_role;
grant execute on function public.store_post_shipment(bigint) to anon, authenticated, service_role;
grant execute on function public.store_post_return(bigint) to anon, authenticated, service_role;
grant execute on function public.store_send_transfer(bigint) to anon, authenticated, service_role;
grant execute on function public.store_complete_transfer(bigint) to anon, authenticated, service_role;
grant execute on function public.store_complete_output(bigint) to anon, authenticated, service_role;
grant execute on function public.store_reverse_source(text, bigint) to anon, authenticated, service_role;
grant execute on function public.store_sync_production_activation(bigint) to anon, authenticated, service_role;
grant execute on function public.store_cancel_document(text, bigint) to anon, authenticated, service_role;

create or replace function public.store_reset_logistics_stories(p_lo bigint, p_hi bigint)
returns text
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if p_lo is null or p_hi is null or p_lo < 901 or p_hi > 999 or p_lo > p_hi then
    raise exception 'Story reset range must stay inside 901-999';
  end if;

  perform set_config('session_replication_role', 'replica', true);

  delete from public.store_stock_transaction
  where (owner_type = 'order' and owner_id between p_lo and p_hi)
     or source_id between p_lo and p_hi
     or source_id in (
       select store_reservation.id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     )
     or source_id in (
       select store_shipment.id from public.store_shipment where customer_order_id between p_lo and p_hi
     )
     or source_id in (
       select r.id from public.store_return r
       join public.store_shipment s on s.id = r.shipment_id
       where s.customer_order_id between p_lo and p_hi or s.id between p_lo and p_hi or r.id between p_lo and p_hi
     )
     or source_id in (
       select store_output.id from public.store_output where id between p_lo and p_hi
     )
     or source_id in (
       select store_production_order.id from public.store_production_order where id between p_lo and p_hi
     )
     or source_id in (
       select store_transfer.id from public.store_transfer where id between p_lo and p_hi
     );

  delete from public.store_return_line
  where id between p_lo and p_hi
     or return_id in (
       select r.id from public.store_return r
       left join public.store_shipment s on s.id = r.shipment_id
       where r.id between p_lo and p_hi
          or s.id between p_lo and p_hi
          or s.customer_order_id between p_lo and p_hi
     );

  delete from public.store_return
  where id between p_lo and p_hi
     or shipment_id in (
       select store_shipment.id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     );

  delete from public.store_shipment_line
  where id between p_lo and p_hi
     or shipment_id in (
       select store_shipment.id from public.store_shipment
       where id between p_lo and p_hi or customer_order_id between p_lo and p_hi
     );

  delete from public.store_shipment
  where id between p_lo and p_hi or customer_order_id between p_lo and p_hi;

  delete from public.store_output_allocation
  where id between p_lo and p_hi
     or (owner_type = 'order' and owner_id between p_lo and p_hi);

  delete from public.store_output_line where id between p_lo and p_hi or output_id between p_lo and p_hi;
  delete from public.store_output where id between p_lo and p_hi;

  delete from public.store_transfer_allocation
  where id between p_lo and p_hi
     or (owner_type = 'order' and owner_id between p_lo and p_hi);

  delete from public.store_transfer_line where id between p_lo and p_hi or transfer_id between p_lo and p_hi;
  delete from public.store_transfer where id between p_lo and p_hi;

  delete from public.store_reservation_line
  where id between p_lo and p_hi
     or (from_owner_type = 'order' and from_owner_id between p_lo and p_hi)
     or reservation_id in (
       select store_reservation.id from public.store_reservation
       where id between p_lo and p_hi
          or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi)
     );

  delete from public.store_reservation
  where id between p_lo and p_hi
     or (to_owner_type = 'order' and to_owner_id between p_lo and p_hi);

  delete from public.store_production_order_line where id between p_lo and p_hi or order_id between p_lo and p_hi;
  delete from public.store_production_order where id between p_lo and p_hi;
  delete from public.store_customer_order_line where id between p_lo and p_hi or order_id between p_lo and p_hi;
  delete from public.store_customer_order where id between p_lo and p_hi;

  perform set_config('session_replication_role', 'origin', true);
  return 'reset';
exception
  when others then
    perform set_config('session_replication_role', 'origin', true);
    raise;
end;
$$;

grant execute on function public.store_reset_logistics_stories(bigint, bigint) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 10. Validate location+product+state totals unchanged
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from (
      select * from store_owner_balance_before
      except
      select product_id, location_type, location_id, stock_state, sum(quantity)
      from public.store_stock_transaction
      group by 1, 2, 3, 4
      having abs(sum(quantity)) > 0.0000001
    ) missing
  ) or exists (
    select 1 from (
      select product_id, location_type, location_id, stock_state, sum(quantity)
      from public.store_stock_transaction
      group by 1, 2, 3, 4
      having abs(sum(quantity)) > 0.0000001
      except
      select * from store_owner_balance_before
    ) extra
  ) then
    raise exception 'Owner reservation migration changed location+product stock totals';
  end if;
end;
$$;

drop table store_owner_balance_before;

notify pgrst, 'reload schema';

commit;
