-- Convert remapped text ids to bigint identity columns and restore FKs.

alter table public.logistics_transfer drop constraint if exists logistics_transfer_check;

do $$
declare
  r record;
begin
  for r in
    select table_name, column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name like 'logistics_%'
      and table_name <> 'logistics_stock_balance'
      and data_type = 'text'
      and (
        column_name = 'id'
        or column_name = 'transaction_id'
        or (
          column_name like '%_id'
          and column_name not in ('operation_id')
        )
      )
  loop
    execute format(
      'alter table public.%I alter column %I type bigint using %I::bigint',
      r.table_name, r.column_name, r.column_name
    );
  end loop;
end
$$;

do $$
declare
  r record;
  has_rows boolean;
  current_max bigint;
begin
  for r in
    select c.relname as table_name, a.attname as column_name
    from pg_index i
    join pg_class c on c.oid = i.indrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum = any(i.indkey)
    where n.nspname = 'public'
      and c.relname like 'logistics_%'
      and c.relkind = 'r'
      and i.indisprimary
  loop
    execute format(
      'alter table public.%I alter column %I add generated by default as identity',
      r.table_name, r.column_name
    );
    execute format('select exists(select 1 from public.%I)', r.table_name) into has_rows;
    execute format('select coalesce(max(%I), 1) from public.%I', r.column_name, r.table_name) into current_max;
    perform setval(
      pg_get_serial_sequence(format('public.%I', r.table_name), r.column_name),
      current_max,
      has_rows
    );
  end loop;
end
$$;

alter table public.logistics_warehouse
  add constraint logistics_warehouse_manufacturer_id_fkey
  foreign key (manufacturer_id) references public.logistics_manufacturer (id);

alter table public.logistics_manufacturer
  add constraint logistics_manufacturer_warehouse_id_fkey
  foreign key (warehouse_id) references public.logistics_warehouse (id);

alter table public.logistics_product_manufacturer
  add constraint logistics_product_manufacturer_product_id_fkey
  foreign key (product_id) references public.logistics_product (id) on delete cascade;
alter table public.logistics_product_manufacturer
  add constraint logistics_product_manufacturer_manufacturer_id_fkey
  foreign key (manufacturer_id) references public.logistics_manufacturer (id) on delete cascade;

alter table public.logistics_customer_order_line
  add constraint logistics_customer_order_line_order_id_fkey
  foreign key (order_id) references public.logistics_customer_order (id) on delete cascade;
alter table public.logistics_customer_order_line
  add constraint logistics_customer_order_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_production_order
  add constraint logistics_production_order_manufacturer_id_fkey
  foreign key (manufacturer_id) references public.logistics_manufacturer (id);

alter table public.logistics_production_order_line
  add constraint logistics_production_order_line_order_id_fkey
  foreign key (order_id) references public.logistics_production_order (id) on delete cascade;
alter table public.logistics_production_order_line
  add constraint logistics_production_order_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_reservation
  add constraint logistics_reservation_customer_order_id_fkey
  foreign key (customer_order_id) references public.logistics_customer_order (id);

alter table public.logistics_reservation_line
  add constraint logistics_reservation_line_reservation_id_fkey
  foreign key (reservation_id) references public.logistics_reservation (id) on delete cascade;
alter table public.logistics_reservation_line
  add constraint logistics_reservation_line_customer_order_line_id_fkey
  foreign key (customer_order_line_id) references public.logistics_customer_order_line (id);
alter table public.logistics_reservation_line
  add constraint logistics_reservation_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_reservation_release
  add constraint logistics_reservation_release_customer_order_id_fkey
  foreign key (customer_order_id) references public.logistics_customer_order (id);

alter table public.logistics_reservation_release_line
  add constraint logistics_reservation_release_line_release_id_fkey
  foreign key (release_id) references public.logistics_reservation_release (id) on delete cascade;
alter table public.logistics_reservation_release_line
  add constraint logistics_reservation_release_line_customer_order_line_id_fkey
  foreign key (customer_order_line_id) references public.logistics_customer_order_line (id);
alter table public.logistics_reservation_release_line
  add constraint logistics_reservation_release_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_transfer
  add constraint logistics_transfer_from_warehouse_id_fkey
  foreign key (from_warehouse_id) references public.logistics_warehouse (id);
alter table public.logistics_transfer
  add constraint logistics_transfer_to_warehouse_id_fkey
  foreign key (to_warehouse_id) references public.logistics_warehouse (id);
alter table public.logistics_transfer
  add constraint logistics_transfer_check
  check (from_warehouse_id <> to_warehouse_id);

alter table public.logistics_transfer_line
  add constraint logistics_transfer_line_transfer_id_fkey
  foreign key (transfer_id) references public.logistics_transfer (id) on delete cascade;
alter table public.logistics_transfer_line
  add constraint logistics_transfer_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_transfer_allocation
  add constraint logistics_transfer_allocation_line_id_fkey
  foreign key (line_id) references public.logistics_transfer_line (id) on delete cascade;
alter table public.logistics_transfer_allocation
  add constraint logistics_transfer_allocation_customer_order_id_fkey
  foreign key (customer_order_id) references public.logistics_customer_order (id);
alter table public.logistics_transfer_allocation
  add constraint logistics_transfer_allocation_customer_order_line_id_fkey
  foreign key (customer_order_line_id) references public.logistics_customer_order_line (id);

alter table public.logistics_shipment
  add constraint logistics_shipment_customer_order_id_fkey
  foreign key (customer_order_id) references public.logistics_customer_order (id);
alter table public.logistics_shipment
  add constraint logistics_shipment_warehouse_id_fkey
  foreign key (warehouse_id) references public.logistics_warehouse (id);

alter table public.logistics_shipment_line
  add constraint logistics_shipment_line_shipment_id_fkey
  foreign key (shipment_id) references public.logistics_shipment (id) on delete cascade;
alter table public.logistics_shipment_line
  add constraint logistics_shipment_line_customer_order_line_id_fkey
  foreign key (customer_order_line_id) references public.logistics_customer_order_line (id);
alter table public.logistics_shipment_line
  add constraint logistics_shipment_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_output
  add constraint logistics_output_production_order_id_fkey
  foreign key (production_order_id) references public.logistics_production_order (id);

alter table public.logistics_output_line
  add constraint logistics_output_line_output_id_fkey
  foreign key (output_id) references public.logistics_output (id) on delete cascade;
alter table public.logistics_output_line
  add constraint logistics_output_line_production_order_line_id_fkey
  foreign key (production_order_line_id) references public.logistics_production_order_line (id);
alter table public.logistics_output_line
  add constraint logistics_output_line_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

alter table public.logistics_output_allocation
  add constraint logistics_output_allocation_line_id_fkey
  foreign key (line_id) references public.logistics_output_line (id) on delete cascade;
alter table public.logistics_output_allocation
  add constraint logistics_output_allocation_customer_order_id_fkey
  foreign key (customer_order_id) references public.logistics_customer_order (id);
alter table public.logistics_output_allocation
  add constraint logistics_output_allocation_customer_order_line_id_fkey
  foreign key (customer_order_line_id) references public.logistics_customer_order_line (id);

alter table public.logistics_return
  add constraint logistics_return_shipment_id_fkey
  foreign key (shipment_id) references public.logistics_shipment (id);

alter table public.logistics_return_line
  add constraint logistics_return_line_return_id_fkey
  foreign key (return_id) references public.logistics_return (id) on delete cascade;
alter table public.logistics_return_line
  add constraint logistics_return_line_shipment_line_id_fkey
  foreign key (shipment_line_id) references public.logistics_shipment_line (id);

alter table public.logistics_stock_transaction
  add constraint logistics_stock_transaction_product_id_fkey
  foreign key (product_id) references public.logistics_product (id);

create or replace view public.logistics_stock_balance as
select
  product_id,
  location_type,
  location_id,
  stock_state,
  customer_order_id,
  customer_order_line_id,
  sum(quantity) as quantity
from public.logistics_stock_transaction
group by 1, 2, 3, 4, 5, 6
having abs(sum(quantity)) > 0.0000001;

grant select on public.logistics_stock_balance to anon, authenticated, service_role;

create or replace function public.logistics_code(p_kind text, p_id bigint)
returns text
language sql
immutable
as $$
  select case p_kind
    when 'product' then 'PRD-' || p_id
    when 'manufacturer' then 'PLT-' || p_id
    when 'warehouse' then 'WH-' || p_id
    when 'customer_order' then 'OMS-' || p_id
    when 'production_order' then 'PO-' || p_id
    when 'reservation' then 'RSV-' || p_id
    when 'reservation_release' then 'REL-' || p_id
    when 'transfer' then 'TR-' || p_id
    when 'shipment' then 'SHP-' || p_id
    when 'output' then 'OUT-' || p_id
    when 'return' then 'RET-' || p_id
    when 'customer_order_line' then 'COL-' || p_id
    when 'production_order_line' then 'POL-' || p_id
    when 'reservation_line' then 'RSVL-' || p_id
    when 'reservation_release_line' then 'RELL-' || p_id
    when 'transfer_line' then 'TRL-' || p_id
    when 'transfer_allocation' then 'TRA-' || p_id
    when 'shipment_line' then 'SHL-' || p_id
    when 'output_line' then 'OUTL-' || p_id
    when 'output_allocation' then 'OUA-' || p_id
    when 'return_line' then 'RETL-' || p_id
    when 'product_manufacturer' then 'PM-' || p_id
    when 'stock_transaction' then 'TXN-' || p_id
    when 'setting' then 'SET-' || p_id
    else p_kind || '-' || p_id
  end;
$$;

grant execute on function public.logistics_code(text, bigint) to anon, authenticated, service_role;
