-- Universal document registry + product lines (part A: schema & data)
-- Spec: spec-universal-document-product-lines

begin;

create table public.store_document (
  id bigint generated by default as identity primary key,
  kind text not null
    check (kind in (
      'customer_order', 'production_order', 'reservation', 'transfer',
      'shipment', 'output', 'adjustment'
    )),
  series text not null,
  sequence_number bigint not null,
  created_at timestamptz not null default now(),
  created_by bigint not null references public.store_user(id),
  unique (series, sequence_number)
);

create table public.store_product_region_offer (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.store_product(id) on delete cascade,
  region_id bigint not null references public.store_region(id) on delete cascade,
  purchase_price numeric,
  purchase_currency text,
  dealer_price numeric,
  dealer_currency text,
  retail_price numeric,
  retail_currency text,
  dealer_status text not null
    check (dealer_status in ('available', 'unavailable')),
  retail_status text not null
    check (retail_status in (
      'draft', 'available', 'preorder', 'temporarily_unavailable',
      'discontinued', 'banned', 'hidden', 'pending_approval', 'archived'
    )),
  unique (product_id, region_id)
);

create table public.store_document_product_line (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.store_document(id) on delete cascade,
  product_id bigint references public.store_product(id) on delete set null,
  manufacturer_id bigint references public.store_manufacturer(id) on delete set null,
  quantity numeric not null check (quantity > 0),
  from_owner_type text,
  from_owner_id bigint,
  to_owner_type text,
  to_owner_id bigint,
  product_name text not null,
  product_sku text not null,
  product_unit text not null,
  variant text,
  manufacturer_name text,
  manufacturer_code text,
  constraint store_document_product_line_from_owner_chk
    check ((from_owner_type is null) = (from_owner_id is null)),
  constraint store_document_product_line_to_owner_chk
    check ((to_owner_type is null) = (to_owner_id is null)),
  constraint store_document_product_line_from_owner_type_chk
    check (from_owner_type is null or from_owner_type in ('order', 'region')),
  constraint store_document_product_line_to_owner_type_chk
    check (to_owner_type is null or to_owner_type in ('order', 'region'))
);

create unique index store_document_product_line_owner_uidx
  on public.store_document_product_line (
    document_id,
    coalesce(product_id, 0),
    coalesce(from_owner_type, ''),
    coalesce(from_owner_id, 0),
    coalesce(to_owner_type, ''),
    coalesce(to_owner_id, 0)
  );

create table public.store_document_product_line_region_snapshot (
  id bigint generated by default as identity primary key,
  line_id bigint not null references public.store_document_product_line(id) on delete cascade,
  region_id bigint references public.store_region(id) on delete set null,
  region_code text not null,
  region_name text not null,
  purchase_price numeric,
  purchase_currency text,
  dealer_price numeric,
  dealer_currency text,
  retail_price numeric,
  retail_currency text,
  dealer_status text,
  retail_status text
);

create unique index store_dpl_region_snapshot_uidx
  on public.store_document_product_line_region_snapshot (line_id, coalesce(region_id, 0), region_code);

alter table public.store_document enable row level security;
alter table public.store_product_region_offer enable row level security;
alter table public.store_document_product_line enable row level security;
alter table public.store_document_product_line_region_snapshot enable row level security;

create policy store_document_all on public.store_document for all to anon, authenticated using (true) with check (true);
create policy store_product_region_offer_all on public.store_product_region_offer for all to anon, authenticated using (true) with check (true);
create policy store_document_product_line_all on public.store_document_product_line for all to anon, authenticated using (true) with check (true);
create policy store_dpl_region_snapshot_all on public.store_document_product_line_region_snapshot for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on table public.store_document to anon, authenticated, service_role;
grant select, insert, update, delete on table public.store_product_region_offer to anon, authenticated, service_role;
grant select, insert, update, delete on table public.store_document_product_line to anon, authenticated, service_role;
grant select, insert, update, delete on table public.store_document_product_line_region_snapshot to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

insert into public.store_product_region_offer (
  product_id, region_id,
  purchase_price, purchase_currency,
  dealer_price, dealer_currency,
  retail_price, retail_currency,
  dealer_status, retail_status
)
select
  p.id, r.id,
  null, null,
  p.dealer_price, case when p.dealer_price is null then null else 'USD' end,
  p.retail_price, case when p.retail_price is null then null else 'USD' end,
  case when p.dealer_price is null then 'unavailable' else 'available' end,
  case when p.retail_price is null then 'draft' else 'available' end
from public.store_product p
cross join public.store_region r;

create or replace function public.store_document_series(p_kind text)
returns text
language sql
stable
as $f$
  select coalesce(
    nullif(
      (
        select s.code_prefixes ->> public.store_code_kind_key(p_kind)
        from public.store_setting s
        order by s.id
        limit 1
      ),
      ''
    ),
    case p_kind
      when 'customer_order' then 'OMS'
      when 'production_order' then 'PO'
      when 'reservation' then 'RSV'
      when 'transfer' then 'TR'
      when 'shipment' then 'SHP'
      when 'output' then 'OUT'
      when 'adjustment' then 'ADJ'
      else upper(p_kind)
    end
  );
$f$;

grant execute on function public.store_document_series(text) to anon, authenticated, service_role;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id, 'customer_order', public.store_document_series('customer_order'), id, created_at, created_by
from public.store_customer_order;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id + 2000000, 'production_order', public.store_document_series('production_order'), id, created_at, created_by
from public.store_production_order;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id + 3000000, 'reservation', public.store_document_series('reservation'), id, created_at, created_by
from public.store_reservation;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id + 4000000, 'transfer', public.store_document_series('transfer'), id, created_at, created_by
from public.store_transfer;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id + 5000000, 'shipment', public.store_document_series('shipment'), id, created_at, created_by
from public.store_shipment;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id + 6000000, 'output', public.store_document_series('output'), id, created_at, created_by
from public.store_output;

insert into public.store_document (id, kind, series, sequence_number, created_at, created_by)
select id + 7000000, 'adjustment', public.store_document_series('adjustment'), id, created_at, created_by
from public.store_adjustment;

select setval(
  pg_get_serial_sequence('public.store_document', 'id'),
  greatest(8000000, (select coalesce(max(id), 1) from public.store_document))
);

-- Disable guards while remapping ids
alter table public.store_reservation disable trigger all;
alter table public.store_reservation_line disable trigger all;
alter table public.store_stock_transaction disable trigger all;
alter table public.store_transfer_allocation disable trigger all;
alter table public.store_shipment_line disable trigger all;
alter table public.store_output_allocation disable trigger all;
alter table public.store_customer_order disable trigger all;
alter table public.store_production_order disable trigger all;
alter table public.store_output disable trigger all;
alter table public.store_transfer disable trigger all;

update public.store_stock_transaction set document_id = document_id + 2000000 where document_type = 'production_order';
update public.store_stock_transaction set document_id = document_id + 3000000 where document_type = 'reservation';
update public.store_stock_transaction set document_id = document_id + 4000000 where document_type = 'transfer';
update public.store_stock_transaction set document_id = document_id + 5000000 where document_type = 'shipment';
update public.store_stock_transaction set document_id = document_id + 6000000 where document_type = 'output';
update public.store_stock_transaction set document_id = document_id + 7000000 where document_type = 'adjustment';
update public.store_stock_transaction set document_id = document_id + 5000000 where document_type = 'return';
update public.store_stock_transaction set location_id = location_id + 2000000 where location_type = 'production_order';
update public.store_stock_transaction set location_id = location_id + 4000000 where location_type = 'transfer';

update public.store_document_history set document_id = document_id + 2000000 where document_type = 'production_order';
update public.store_document_history set document_id = document_id + 3000000 where document_type = 'reservation';
update public.store_document_history set document_id = document_id + 4000000 where document_type = 'transfer';
update public.store_document_history set document_id = document_id + 5000000 where document_type in ('shipment', 'return');
update public.store_document_history set document_id = document_id + 6000000 where document_type = 'output';
update public.store_document_history set document_id = document_id + 7000000 where document_type = 'adjustment';

update public.store_reservation set location_id = location_id + 2000000 where location_type = 'production_order';
update public.store_reservation set location_id = location_id + 4000000 where location_type = 'transfer';

update public.store_adjustment set source_document_id = source_document_id + 2000000 where source_document_type = 'production_order';
update public.store_adjustment set source_document_id = source_document_id + 3000000 where source_document_type = 'reservation';
update public.store_adjustment set source_document_id = source_document_id + 4000000 where source_document_type = 'transfer';
update public.store_adjustment set source_document_id = source_document_id + 5000000 where source_document_type in ('shipment', 'return');
update public.store_adjustment set source_document_id = source_document_id + 6000000 where source_document_type = 'output';

alter table public.store_production_order_line drop constraint if exists store_production_order_line_order_id_fkey;
alter table public.store_output_line drop constraint if exists store_output_line_production_order_line_id_fkey;
alter table public.store_output drop constraint if exists store_output_production_order_id_fkey;
alter table public.store_output_request drop constraint if exists store_output_request_output_id_fkey;
alter table public.store_shipment_request drop constraint if exists store_shipment_request_shipment_id_fkey;
alter table public.store_transfer_request drop constraint if exists store_transfer_request_transfer_id_fkey;
alter table public.store_reservation_line drop constraint if exists store_reservation_line_reservation_id_fkey;
alter table public.store_transfer_line drop constraint if exists store_transfer_line_transfer_id_fkey;
alter table public.store_transfer_allocation drop constraint if exists store_transfer_allocation_line_id_fkey;
alter table public.store_shipment_line drop constraint if exists store_shipment_line_shipment_id_fkey;
alter table public.store_output_line drop constraint if exists store_output_line_output_id_fkey;
alter table public.store_output_allocation drop constraint if exists store_output_allocation_line_id_fkey;
alter table public.store_adjustment_line drop constraint if exists store_adjustment_line_adjustment_id_fkey;

update public.store_production_order_line set order_id = order_id + 2000000;
update public.store_output set production_order_id = production_order_id + 2000000;
update public.store_production_order set id = id + 2000000;

update public.store_reservation_line set reservation_id = reservation_id + 3000000;
update public.store_reservation set id = id + 3000000;

update public.store_transfer_line set transfer_id = transfer_id + 4000000;
update public.store_transfer set id = id + 4000000;

update public.store_shipment_line set shipment_id = shipment_id + 5000000;
update public.store_shipment set id = id + 5000000;

update public.store_output_line set output_id = output_id + 6000000;
update public.store_output_request set output_id = output_id + 6000000;
update public.store_output set id = id + 6000000;

update public.store_shipment_request set shipment_id = shipment_id + 5000000;
update public.store_transfer_request set transfer_id = transfer_id + 4000000;

update public.store_adjustment_line set adjustment_id = adjustment_id + 7000000;
update public.store_adjustment set id = id + 7000000;

-- Re-enable triggers
alter table public.store_reservation enable trigger all;
alter table public.store_reservation_line enable trigger all;
alter table public.store_stock_transaction enable trigger all;
alter table public.store_transfer_allocation enable trigger all;
alter table public.store_shipment_line enable trigger all;
alter table public.store_output_allocation enable trigger all;
alter table public.store_customer_order enable trigger all;
alter table public.store_production_order enable trigger all;
alter table public.store_output enable trigger all;
alter table public.store_transfer enable trigger all;

-- Restore FKs among remapped headers
alter table public.store_production_order_line
  add constraint store_production_order_line_order_id_fkey
  foreign key (order_id) references public.store_production_order(id);
alter table public.store_reservation_line
  add constraint store_reservation_line_reservation_id_fkey
  foreign key (reservation_id) references public.store_reservation(id);
alter table public.store_transfer_line
  add constraint store_transfer_line_transfer_id_fkey
  foreign key (transfer_id) references public.store_transfer(id);
alter table public.store_transfer_allocation
  add constraint store_transfer_allocation_line_id_fkey
  foreign key (line_id) references public.store_transfer_line(id);
alter table public.store_shipment_line
  add constraint store_shipment_line_shipment_id_fkey
  foreign key (shipment_id) references public.store_shipment(id);
alter table public.store_output
  add constraint store_output_production_order_id_fkey
  foreign key (production_order_id) references public.store_production_order(id);
alter table public.store_output_line
  add constraint store_output_line_output_id_fkey
  foreign key (output_id) references public.store_output(id);
alter table public.store_output_request
  add constraint store_output_request_output_id_fkey
  foreign key (output_id) references public.store_output(id);
alter table public.store_shipment_request
  add constraint store_shipment_request_shipment_id_fkey
  foreign key (shipment_id) references public.store_shipment(id);
alter table public.store_transfer_request
  add constraint store_transfer_request_transfer_id_fkey
  foreign key (transfer_id) references public.store_transfer(id);
alter table public.store_adjustment_line
  add constraint store_adjustment_line_adjustment_id_fkey
  foreign key (adjustment_id) references public.store_adjustment(id);

-- Shared PK with store_document
alter table public.store_customer_order
  add constraint store_customer_order_document_fkey foreign key (id) references public.store_document(id);
alter table public.store_production_order
  add constraint store_production_order_document_fkey foreign key (id) references public.store_document(id);
alter table public.store_reservation
  add constraint store_reservation_document_fkey foreign key (id) references public.store_document(id);
alter table public.store_transfer
  add constraint store_transfer_document_fkey foreign key (id) references public.store_document(id);
alter table public.store_shipment
  add constraint store_shipment_document_fkey foreign key (id) references public.store_document(id);
alter table public.store_output
  add constraint store_output_document_fkey foreign key (id) references public.store_document(id);
alter table public.store_adjustment
  add constraint store_adjustment_document_fkey foreign key (id) references public.store_document(id);

alter table public.store_customer_order drop column if exists created_at;
alter table public.store_customer_order drop column if exists created_by;
alter table public.store_production_order drop column if exists created_at;
alter table public.store_production_order drop column if exists created_by;
alter table public.store_reservation drop column if exists created_at;
alter table public.store_reservation drop column if exists created_by;
alter table public.store_transfer drop column if exists created_at;
alter table public.store_transfer drop column if exists created_by;
alter table public.store_shipment drop column if exists created_at;
alter table public.store_shipment drop column if exists created_by;
alter table public.store_output drop column if exists created_at;
alter table public.store_output drop column if exists created_by;
alter table public.store_adjustment drop column if exists created_at;
alter table public.store_adjustment drop column if exists created_by;

-- Helper to copy snapshot fields from product + manufacturer
create or replace function public.store_line_snapshot_fields(p_product_id bigint)
returns table (
  product_name text,
  product_sku text,
  product_unit text,
  manufacturer_id bigint,
  manufacturer_name text,
  manufacturer_code text
)
language sql
stable
as $f$
  select
    p.name,
    p.sku,
    p.unit,
    p.manufacturer_id,
    m.name,
    case when m.id is null then null else public.store_code('manufacturer', m.id) end
  from public.store_product p
  left join public.store_manufacturer m on m.id = p.manufacturer_id
  where p.id = p_product_id;
$f$;

create or replace function public.store_insert_line_region_snapshots(p_line_id bigint, p_product_id bigint)
returns void
language plpgsql
as $f$
declare
  r record;
begin
  for r in
    select
      reg.id as region_id,
      public.store_code('region', reg.id) as region_code,
      reg.name as region_name,
      o.purchase_price, o.purchase_currency,
      o.dealer_price, o.dealer_currency,
      o.retail_price, o.retail_currency,
      o.dealer_status, o.retail_status
    from public.store_region reg
    left join public.store_product_region_offer o
      on o.region_id = reg.id and o.product_id = p_product_id
    order by reg.id
  loop
    insert into public.store_document_product_line_region_snapshot (
      line_id, region_id, region_code, region_name,
      purchase_price, purchase_currency,
      dealer_price, dealer_currency,
      retail_price, retail_currency,
      dealer_status, retail_status
    ) values (
      p_line_id, r.region_id, r.region_code, r.region_name,
      r.purchase_price, r.purchase_currency,
      r.dealer_price, r.dealer_currency,
      r.retail_price, r.retail_currency,
      r.dealer_status, r.retail_status
    );
  end loop;
end;
$f$;

create or replace function public.store_add_document_product_line(
  p_document_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_from_owner_type text default null,
  p_from_owner_id bigint default null,
  p_to_owner_type text default null,
  p_to_owner_id bigint default null
)
returns bigint
language plpgsql
as $f$
declare
  v_line_id bigint;
  v_snap record;
begin
  if coalesce(p_quantity, 0) <= 0 then
    raise exception 'Количество должно быть больше нуля';
  end if;
  if p_product_id is null then
    raise exception 'Укажите товар';
  end if;
  perform public.store_assert_owner(p_from_owner_type, p_from_owner_id);
  perform public.store_assert_owner(p_to_owner_type, p_to_owner_id);

  select * into v_snap from public.store_line_snapshot_fields(p_product_id);
  if v_snap.product_name is null then
    raise exception 'Неизвестный товар %', p_product_id;
  end if;

  insert into public.store_document_product_line (
    document_id, product_id, manufacturer_id, quantity,
    from_owner_type, from_owner_id, to_owner_type, to_owner_id,
    product_name, product_sku, product_unit, variant,
    manufacturer_name, manufacturer_code
  ) values (
    p_document_id, p_product_id, v_snap.manufacturer_id, p_quantity,
    nullif(btrim(coalesce(p_from_owner_type, '')), ''), p_from_owner_id,
    nullif(btrim(coalesce(p_to_owner_type, '')), ''), p_to_owner_id,
    v_snap.product_name, v_snap.product_sku, v_snap.product_unit, null,
    v_snap.manufacturer_name, v_snap.manufacturer_code
  )
  returning id into v_line_id;

  perform public.store_insert_line_region_snapshots(v_line_id, p_product_id);
  return v_line_id;
end;
$f$;

grant execute on function public.store_add_document_product_line(bigint, bigint, numeric, text, bigint, text, bigint)
  to anon, authenticated, service_role;
grant execute on function public.store_insert_line_region_snapshots(bigint, bigint)
  to anon, authenticated, service_role;

-- Migrate lines from legacy tables (using remapped document ids)
-- Customer order lines
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  l.order_id, l.product_id, p.manufacturer_id, l.quantity,
  null, null, null, null,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_customer_order_line l
join public.store_product p on p.id = l.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

-- Production order lines
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  l.order_id, l.product_id, p.manufacturer_id, l.quantity,
  null, null, null, null,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_production_order_line l
join public.store_product p on p.id = l.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

-- Reservation lines: from on line, to on header
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  l.reservation_id, l.product_id, p.manufacturer_id, l.quantity,
  l.from_owner_type, l.from_owner_id, r.to_owner_type, r.to_owner_id,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_reservation_line l
join public.store_reservation r on r.id = l.reservation_id
join public.store_product p on p.id = l.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

-- Transfer: allocations as owned lines; free remainder as null pair
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  tl.transfer_id, tl.product_id, p.manufacturer_id, a.quantity,
  a.owner_type, a.owner_id, a.owner_type, a.owner_id,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_transfer_allocation a
join public.store_transfer_line tl on tl.id = a.line_id
join public.store_product p on p.id = tl.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  tl.transfer_id, tl.product_id, p.manufacturer_id,
  tl.quantity - coalesce((select sum(a.quantity) from public.store_transfer_allocation a where a.line_id = tl.id), 0),
  null, null, null, null,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_transfer_line tl
join public.store_product p on p.id = tl.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id
where tl.quantity - coalesce((select sum(a.quantity) from public.store_transfer_allocation a where a.line_id = tl.id), 0) > 0;

-- Shipment: to from line; from = order (outbound) or to_owner (return inbound)
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  l.shipment_id, l.product_id, p.manufacturer_id, l.quantity,
  case
    when s.from_location_type = 'warehouse' then 'order'
    else l.to_owner_type
  end,
  case
    when s.from_location_type = 'warehouse' then s.customer_order_id
    else l.to_owner_id
  end,
  l.to_owner_type, l.to_owner_id,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_shipment_line l
join public.store_shipment s on s.id = l.shipment_id
join public.store_product p on p.id = l.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

-- Output lines (ignore production_order_line_id / allocations — none in data)
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  l.output_id, l.product_id, p.manufacturer_id, l.quantity,
  null, null, null, null,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_output_line l
join public.store_product p on p.id = l.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

-- Adjustment lines
insert into public.store_document_product_line (
  document_id, product_id, manufacturer_id, quantity,
  from_owner_type, from_owner_id, to_owner_type, to_owner_id,
  product_name, product_sku, product_unit, variant,
  manufacturer_name, manufacturer_code
)
select
  l.adjustment_id, l.product_id, p.manufacturer_id, l.quantity,
  null, null, null, null,
  p.name, p.sku, p.unit, null,
  m.name, case when m.id is null then null else public.store_code('manufacturer', m.id) end
from public.store_adjustment_line l
join public.store_product p on p.id = l.product_id
left join public.store_manufacturer m on m.id = p.manufacturer_id;

-- Region snapshots for every migrated line
do $$
declare
  v_line record;
begin
  for v_line in select id, product_id from public.store_document_product_line
  loop
    perform public.store_insert_line_region_snapshots(v_line.id, v_line.product_id);
  end loop;
end $$;

-- Existing PO stock facts and reservation ledger on production_order: remove
-- (demand assignments remain as reservation documents; stock is not at PO)
delete from public.store_stock_transaction
where location_type = 'production_order';

delete from public.store_stock_transaction
where document_type = 'production_order';

-- Drop legacy line / allocation tables and activated_quantity
drop table if exists public.store_output_allocation cascade;
drop table if exists public.store_transfer_allocation cascade;
drop table if exists public.store_customer_order_line cascade;
drop table if exists public.store_production_order_line cascade;
drop table if exists public.store_reservation_line cascade;
drop table if exists public.store_transfer_line cascade;
drop table if exists public.store_shipment_line cascade;
drop table if exists public.store_output_line cascade;
drop table if exists public.store_adjustment_line cascade;

drop function if exists public.store_sync_production_activation(bigint);

commit;
